apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agent-install.openshift.io_agents.yaml
- agent-install.openshift.io_infraenvs.yaml
- hive.openshift.io_clusterdeployments.yaml
- hypershift.openshift.io_hostedclusters.yaml
- hypershift.openshift.io_hostedcontrolplanes.yaml
- hypershift.openshift.io_nodepools.yaml
- k8s.ovn.org_userdefinednetworks.yaml
- kubevirt.io_virtualmachineinstances.yaml
- kubevirt.io_virtualmachines.yaml
- osac.openshift.io_baremetalinstances.yaml
