// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/proto/gen/osac/private/v1 (interfaces: BareMetalInstancesClient)
//
// Generated by this command:
//
//	mockgen -destination=bare_metal_instances_client_mock.go -package=baremetalinstance github.com/osac-project/osac/proto/gen/osac/private/v1 BareMetalInstancesClient
//

// Package baremetalinstance is a generated GoMock package.
package baremetalinstance

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	privatev1 "github.com/osac-project/osac/proto/gen/osac/private/v1"
)

// MockBareMetalInstancesClient is a mock of BareMetalInstancesClient interface.
type MockBareMetalInstancesClient struct {
	ctrl     *gomock.Controller
	recorder *MockBareMetalInstancesClientMockRecorder
	isgomock struct{}
}

// MockBareMetalInstancesClientMockRecorder is the mock recorder for MockBareMetalInstancesClient.
type MockBareMetalInstancesClientMockRecorder struct {
	mock *MockBareMetalInstancesClient
}

// NewMockBareMetalInstancesClient creates a new mock instance.
func NewMockBareMetalInstancesClient(ctrl *gomock.Controller) *MockBareMetalInstancesClient {
	mock := &MockBareMetalInstancesClient{ctrl: ctrl}
	mock.recorder = &MockBareMetalInstancesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBareMetalInstancesClient) EXPECT() *MockBareMetalInstancesClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBareMetalInstancesClient) Create(ctx context.Context, in *privatev1.BareMetalInstancesCreateRequest, opts ...grpc.CallOption) (*privatev1.BareMetalInstancesCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.BareMetalInstancesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBareMetalInstancesClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBareMetalInstancesClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockBareMetalInstancesClient) Delete(ctx context.Context, in *privatev1.BareMetalInstancesDeleteRequest, opts ...grpc.CallOption) (*privatev1.BareMetalInstancesDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.BareMetalInstancesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockBareMetalInstancesClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBareMetalInstancesClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockBareMetalInstancesClient) Get(ctx context.Context, in *privatev1.BareMetalInstancesGetRequest, opts ...grpc.CallOption) (*privatev1.BareMetalInstancesGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.BareMetalInstancesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBareMetalInstancesClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBareMetalInstancesClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockBareMetalInstancesClient) List(ctx context.Context, in *privatev1.BareMetalInstancesListRequest, opts ...grpc.CallOption) (*privatev1.BareMetalInstancesListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.BareMetalInstancesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBareMetalInstancesClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBareMetalInstancesClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockBareMetalInstancesClient) Signal(ctx context.Context, in *privatev1.BareMetalInstancesSignalRequest, opts ...grpc.CallOption) (*privatev1.BareMetalInstancesSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.BareMetalInstancesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockBareMetalInstancesClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockBareMetalInstancesClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockBareMetalInstancesClient) Update(ctx context.Context, in *privatev1.BareMetalInstancesUpdateRequest, opts ...grpc.CallOption) (*privatev1.BareMetalInstancesUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.BareMetalInstancesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBareMetalInstancesClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBareMetalInstancesClient)(nil).Update), varargs...)
}
