{{- $serviceDb := include "osac.dbNameService" . }}
{{- $meteringDb := include "osac.dbNameMetering" . }}
{{- $dbHost := .Values.dbInit.host | default "postgres.osac-infra.svc.cluster.local" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "osac.fullname" . }}-db-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
spec:
  issuerRef:
    kind: {{ .Values.service.certs.issuerRef.kind }}
    name: {{ .Values.service.certs.issuerRef.name }}
  commonName: {{ $serviceDb }}
  usages:
  - client auth
  secretName: {{ include "osac.fullname" . }}-db-client-cert
  privateKey:
    encoding: PKCS8
    rotationPolicy: Always
  additionalOutputFormats:
  - type: DER
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osac.fullname" . }}-db-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "postgres://{{ $serviceDb }}@{{ $dbHost }}:5432/{{ $serviceDb }}?sslmode=verify-full&sslrootcert=/etc/fulfillment-grpc-server/db/sslrootcert&sslcert=/etc/fulfillment-grpc-server/db/sslcert&sslkey=/etc/fulfillment-grpc-server/db/sslkey"
{{- if .Values.metering.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "osac.fullname" . }}-db-metering-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
spec:
  issuerRef:
    kind: {{ .Values.service.certs.issuerRef.kind }}
    name: {{ .Values.service.certs.issuerRef.name }}
  commonName: {{ $meteringDb }}
  usages:
  - client auth
  secretName: {{ include "osac.fullname" . }}-db-metering-client-cert
  privateKey:
    encoding: PKCS8
    rotationPolicy: Always
  additionalOutputFormats:
  - type: DER
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osac.fullname" . }}-db-metering-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "postgres://{{ $meteringDb }}@{{ $dbHost }}:5432/{{ $meteringDb }}?sslmode=verify-full&sslrootcert=/etc/metering/db/sslrootcert&sslcert=/etc/metering/db/sslcert&sslkey=/etc/metering/db/sslkey"
{{- end }}
