apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configAsCode.secret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
stringData:
  {{- with .Values.configAsCode.eeImage }}
  AAP_EE_IMAGE: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.eeImagePull }}
  AAP_EE_IMAGE_PULL: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.projectGitUri }}
  AAP_PROJECT_GIT_URI: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.projectGitBranch }}
  AAP_PROJECT_GIT_BRANCH: {{ . | quote }}
  {{- end }}
