version: 1

workflows:
  - command: e2e-bmaas-netris-full-install
    workflow: e2e-bmaas-netris-full-install-caller.yml
    name: E2E BMaaS Netris Full Install
    description: BMaaS networking tests on the Netris infrastructure
    trigger: label
    label: e2e-bmaas-netris
    retestable: true
