---
- name: Build one NodePool definition per requested NodeSet
  ansible.builtin.set_fact:
    nodepool_definitions: >-
      {{ nodepool_definitions | default([]) + [{
        'apiVersion': 'hypershift.openshift.io/v1beta1',
        'kind': 'NodePool',
        'metadata': {
          'name': nodepool_prefix + '-' + item.nodeSet,
          'namespace': hosted_cluster_namespace,
          'labels': {agent_instance_type_label: item.bareMetal.instanceType, agent_node_set_label: item.nodeSet}
            | combine(hosted_cluster_default_cluster_order_label)
        },
        'spec': {
          'clusterName': hosted_cluster_name,
          'replicas': item.numberOfNodes | int,
          'management': {
            'autoRepair': false,
            'upgradeType': 'InPlace'
          },
          'platform': {
            'type': 'Agent',
            'agent': {
              'agentLabelSelector': {
                'matchLabels': {agent_node_set_label: item.nodeSet} | combine(hosted_cluster_default_cluster_order_label)
              }
            }
          },
          'release': {
            'image': ocp_release_image
          }
        }
      }] }}
  loop: "{{ hosted_cluster_node_requests }}"
  loop_control:
    label: "{{ item.nodeSet }}"
