apiVersion: v2
name: osac
description: Open Sovereign AI Cloud
type: application
version: 0.0.1

dependencies:
  - name: osac-operator-crds
    version: ">=0.0.0"
    repository: "file://../../../osac-operator/charts/operator-crds"
    alias: operatorCrds
  - name: osac-operator
    version: ">=0.0.0"
    repository: "file://../../../osac-operator/charts/operator"
    alias: operator
    condition: operator.enabled
  - name: fulfillment-service
    version: ">=0.0.0"
    repository: "file://../../../fulfillment-service/charts/service"
    alias: service
    condition: service.enabled
  - name: osac-aap
    version: ">=0.0.0"
    repository: "file://../../../osac-aap/charts/aap"
    alias: aap
  - name: bare-metal-fulfillment-operator-crds
    version: ">=0.0.0"
    repository: "file://../../../bare-metal-fulfillment-operator/charts/operator-crds"
    alias: bmfCrds
  - name: bare-metal-fulfillment-operator
    version: ">=0.0.0"
    repository: "file://../../../bare-metal-fulfillment-operator/charts/operator"
    alias: bmf
    condition: bmf.enabled
  - name: osac-ui
    version: "0.0.5"
    repository: "oci://ghcr.io/osac-project/charts"
    alias: ui
    condition: ui.enabled
  - name: osac-metering
    version: ">=0.0.0"
    repository: "file://../../../osac-metering/charts/osac-metering"
    alias: metering
    condition: metering.enabled
  - name: csi-driver
    version: ">=0.0.0"
    repository: "file://../../../osac-csi-driver/charts/csi-driver"
    alias: csiDriver
    condition: csiDriver.enabled
  - name: csi-backends
    version: ">=0.0.0"
    repository: "file://../../../osac-csi-driver/charts/csi-backends"
    alias: csiBackends
    condition: csiDriver.enabled
