apiVersion: v1
kind: ConfigMap
metadata:
  name: osac-deps-hook-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-deps.labels" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "files/hooks/*.sh" }}
  {{ $path | base }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
