dns_ttl: 1800
default_agent_namespace: "{{ (osac_job_vars.resource.metadata.namespace | default('')) if (osac_job_vars is defined and osac_job_vars.resource is defined) else 'hardware-inventory' }}"
manage_agents_namespace: "{{ (osac_job_vars.resource.metadata.namespace | default('')) if (osac_job_vars is defined and osac_job_vars.resource is defined) else 'hardware-inventory' }}"
external_access_agent_namespace: "{{ (osac_job_vars.resource.metadata.namespace | default('')) if (osac_job_vars is defined and osac_job_vars.resource is defined) else 'hardware-inventory' }}"

# Cluster settings credentials (used by cluster_settings role)
cluster_settings_default_credentials_secret_namespace: "default"
cluster_settings_default_credentials_secret_name: "cluster-credentials"

# Hosted cluster defaults
hosted_cluster_default_agent_namespace: "{{ (osac_job_vars.resource.metadata.namespace | default('')) if (osac_job_vars is defined and osac_job_vars.resource is defined) else 'hardware-inventory' }}"
hosted_cluster_default_infraenv: "infraenv"
