// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/proto/gen/osac/private/v1 (interfaces: DiskImagesClient)
//
// Generated by this command:
//
//	mockgen -destination=disk_images_client_mock.go -package=computeinstance github.com/osac-project/osac/proto/gen/osac/private/v1 DiskImagesClient
//

// Package computeinstance is a generated GoMock package.
package computeinstance

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	privatev1 "github.com/osac-project/osac/proto/gen/osac/private/v1"
)

// MockDiskImagesClient is a mock of DiskImagesClient interface.
type MockDiskImagesClient struct {
	ctrl     *gomock.Controller
	recorder *MockDiskImagesClientMockRecorder
	isgomock struct{}
}

// MockDiskImagesClientMockRecorder is the mock recorder for MockDiskImagesClient.
type MockDiskImagesClientMockRecorder struct {
	mock *MockDiskImagesClient
}

// NewMockDiskImagesClient creates a new mock instance.
func NewMockDiskImagesClient(ctrl *gomock.Controller) *MockDiskImagesClient {
	mock := &MockDiskImagesClient{ctrl: ctrl}
	mock.recorder = &MockDiskImagesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiskImagesClient) EXPECT() *MockDiskImagesClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDiskImagesClient) Create(ctx context.Context, in *privatev1.DiskImagesCreateRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDiskImagesClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDiskImagesClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockDiskImagesClient) Delete(ctx context.Context, in *privatev1.DiskImagesDeleteRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDiskImagesClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDiskImagesClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockDiskImagesClient) Get(ctx context.Context, in *privatev1.DiskImagesGetRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDiskImagesClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDiskImagesClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockDiskImagesClient) List(ctx context.Context, in *privatev1.DiskImagesListRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDiskImagesClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDiskImagesClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockDiskImagesClient) Signal(ctx context.Context, in *privatev1.DiskImagesSignalRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockDiskImagesClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockDiskImagesClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockDiskImagesClient) Update(ctx context.Context, in *privatev1.DiskImagesUpdateRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDiskImagesClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDiskImagesClient)(nil).Update), varargs...)
}
