// Code generated by MockGen. DO NOT EDIT.
// Source: ../proto/gen/osac/private/v1/virtual_networks_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../proto/gen/osac/private/v1/virtual_networks_service_grpc.pb.go -destination=internal/controllers/securitygroup/mock_virtualnetworks_client_test.go -package=securitygroup VirtualNetworksClient
//

// Package securitygroup is a generated GoMock package.
package securitygroup

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/osac/proto/gen/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockVirtualNetworksClient is a mock of VirtualNetworksClient interface.
type MockVirtualNetworksClient struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualNetworksClientMockRecorder
	isgomock struct{}
}

// MockVirtualNetworksClientMockRecorder is the mock recorder for MockVirtualNetworksClient.
type MockVirtualNetworksClientMockRecorder struct {
	mock *MockVirtualNetworksClient
}

// NewMockVirtualNetworksClient creates a new mock instance.
func NewMockVirtualNetworksClient(ctrl *gomock.Controller) *MockVirtualNetworksClient {
	mock := &MockVirtualNetworksClient{ctrl: ctrl}
	mock.recorder = &MockVirtualNetworksClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualNetworksClient) EXPECT() *MockVirtualNetworksClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVirtualNetworksClient) Create(ctx context.Context, in *privatev1.VirtualNetworksCreateRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVirtualNetworksClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVirtualNetworksClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockVirtualNetworksClient) Delete(ctx context.Context, in *privatev1.VirtualNetworksDeleteRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockVirtualNetworksClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVirtualNetworksClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockVirtualNetworksClient) Get(ctx context.Context, in *privatev1.VirtualNetworksGetRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVirtualNetworksClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVirtualNetworksClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockVirtualNetworksClient) List(ctx context.Context, in *privatev1.VirtualNetworksListRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVirtualNetworksClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVirtualNetworksClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockVirtualNetworksClient) Signal(ctx context.Context, in *privatev1.VirtualNetworksSignalRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockVirtualNetworksClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockVirtualNetworksClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockVirtualNetworksClient) Update(ctx context.Context, in *privatev1.VirtualNetworksUpdateRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVirtualNetworksClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVirtualNetworksClient)(nil).Update), varargs...)
}

// MockVirtualNetworksServer is a mock of VirtualNetworksServer interface.
type MockVirtualNetworksServer struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualNetworksServerMockRecorder
	isgomock struct{}
}

// MockVirtualNetworksServerMockRecorder is the mock recorder for MockVirtualNetworksServer.
type MockVirtualNetworksServerMockRecorder struct {
	mock *MockVirtualNetworksServer
}

// NewMockVirtualNetworksServer creates a new mock instance.
func NewMockVirtualNetworksServer(ctrl *gomock.Controller) *MockVirtualNetworksServer {
	mock := &MockVirtualNetworksServer{ctrl: ctrl}
	mock.recorder = &MockVirtualNetworksServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualNetworksServer) EXPECT() *MockVirtualNetworksServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVirtualNetworksServer) Create(arg0 context.Context, arg1 *privatev1.VirtualNetworksCreateRequest) (*privatev1.VirtualNetworksCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVirtualNetworksServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVirtualNetworksServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockVirtualNetworksServer) Delete(arg0 context.Context, arg1 *privatev1.VirtualNetworksDeleteRequest) (*privatev1.VirtualNetworksDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockVirtualNetworksServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVirtualNetworksServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockVirtualNetworksServer) Get(arg0 context.Context, arg1 *privatev1.VirtualNetworksGetRequest) (*privatev1.VirtualNetworksGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVirtualNetworksServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVirtualNetworksServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockVirtualNetworksServer) List(arg0 context.Context, arg1 *privatev1.VirtualNetworksListRequest) (*privatev1.VirtualNetworksListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVirtualNetworksServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVirtualNetworksServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockVirtualNetworksServer) Signal(arg0 context.Context, arg1 *privatev1.VirtualNetworksSignalRequest) (*privatev1.VirtualNetworksSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockVirtualNetworksServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockVirtualNetworksServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockVirtualNetworksServer) Update(arg0 context.Context, arg1 *privatev1.VirtualNetworksUpdateRequest) (*privatev1.VirtualNetworksUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVirtualNetworksServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVirtualNetworksServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedVirtualNetworksServer mocks base method.
func (m *MockVirtualNetworksServer) mustEmbedUnimplementedVirtualNetworksServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedVirtualNetworksServer")
}

// mustEmbedUnimplementedVirtualNetworksServer indicates an expected call of mustEmbedUnimplementedVirtualNetworksServer.
func (mr *MockVirtualNetworksServerMockRecorder) mustEmbedUnimplementedVirtualNetworksServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedVirtualNetworksServer", reflect.TypeOf((*MockVirtualNetworksServer)(nil).mustEmbedUnimplementedVirtualNetworksServer))
}

// MockUnsafeVirtualNetworksServer is a mock of UnsafeVirtualNetworksServer interface.
type MockUnsafeVirtualNetworksServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeVirtualNetworksServerMockRecorder
	isgomock struct{}
}

// MockUnsafeVirtualNetworksServerMockRecorder is the mock recorder for MockUnsafeVirtualNetworksServer.
type MockUnsafeVirtualNetworksServerMockRecorder struct {
	mock *MockUnsafeVirtualNetworksServer
}

// NewMockUnsafeVirtualNetworksServer creates a new mock instance.
func NewMockUnsafeVirtualNetworksServer(ctrl *gomock.Controller) *MockUnsafeVirtualNetworksServer {
	mock := &MockUnsafeVirtualNetworksServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeVirtualNetworksServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeVirtualNetworksServer) EXPECT() *MockUnsafeVirtualNetworksServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedVirtualNetworksServer mocks base method.
func (m *MockUnsafeVirtualNetworksServer) mustEmbedUnimplementedVirtualNetworksServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedVirtualNetworksServer")
}

// mustEmbedUnimplementedVirtualNetworksServer indicates an expected call of mustEmbedUnimplementedVirtualNetworksServer.
func (mr *MockUnsafeVirtualNetworksServerMockRecorder) mustEmbedUnimplementedVirtualNetworksServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedVirtualNetworksServer", reflect.TypeOf((*MockUnsafeVirtualNetworksServer)(nil).mustEmbedUnimplementedVirtualNetworksServer))
}
