// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/fulfillment-service/internal/vault (interfaces: TokenSource,TenantTokenSource)
//
// Generated by this command:
//
//	mockgen -destination=vault_token_source_mock.go -package=vault . TokenSource,TenantTokenSource
//

// Package vault is a generated GoMock package.
package vault

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenSource is a mock of TokenSource interface.
type MockTokenSource struct {
	ctrl     *gomock.Controller
	recorder *MockTokenSourceMockRecorder
	isgomock struct{}
}

// MockTokenSourceMockRecorder is the mock recorder for MockTokenSource.
type MockTokenSourceMockRecorder struct {
	mock *MockTokenSource
}

// NewMockTokenSource creates a new mock instance.
func NewMockTokenSource(ctrl *gomock.Controller) *MockTokenSource {
	mock := &MockTokenSource{ctrl: ctrl}
	mock.recorder = &MockTokenSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenSource) EXPECT() *MockTokenSourceMockRecorder {
	return m.recorder
}

// VaultToken mocks base method.
func (m *MockTokenSource) VaultToken(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VaultToken", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VaultToken indicates an expected call of VaultToken.
func (mr *MockTokenSourceMockRecorder) VaultToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VaultToken", reflect.TypeOf((*MockTokenSource)(nil).VaultToken), ctx)
}

// MockTenantTokenSource is a mock of TenantTokenSource interface.
type MockTenantTokenSource struct {
	ctrl     *gomock.Controller
	recorder *MockTenantTokenSourceMockRecorder
	isgomock struct{}
}

// MockTenantTokenSourceMockRecorder is the mock recorder for MockTenantTokenSource.
type MockTenantTokenSourceMockRecorder struct {
	mock *MockTenantTokenSource
}

// NewMockTenantTokenSource creates a new mock instance.
func NewMockTenantTokenSource(ctrl *gomock.Controller) *MockTenantTokenSource {
	mock := &MockTenantTokenSource{ctrl: ctrl}
	mock.recorder = &MockTenantTokenSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantTokenSource) EXPECT() *MockTenantTokenSourceMockRecorder {
	return m.recorder
}

// InvalidateTenantToken mocks base method.
func (m *MockTenantTokenSource) InvalidateTenantToken(tenant string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateTenantToken", tenant)
}

// InvalidateTenantToken indicates an expected call of InvalidateTenantToken.
func (mr *MockTenantTokenSourceMockRecorder) InvalidateTenantToken(tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateTenantToken", reflect.TypeOf((*MockTenantTokenSource)(nil).InvalidateTenantToken), tenant)
}

// VaultToken mocks base method.
func (m *MockTenantTokenSource) VaultToken(ctx context.Context, tenant string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VaultToken", ctx, tenant)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VaultToken indicates an expected call of VaultToken.
func (mr *MockTenantTokenSourceMockRecorder) VaultToken(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VaultToken", reflect.TypeOf((*MockTenantTokenSource)(nil).VaultToken), ctx, tenant)
}
