//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/capabilities_service.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { AuthnCapabilities } from "./authn_capabilities_type_pb";
import { file_osac_private_v1_authn_capabilities_type } from "./authn_capabilities_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/capabilities_service.proto.
 */
export const file_osac_private_v1_capabilities_service: GenFile = /*@__PURE__*/
  fileDesc("Cipvc2FjL3ByaXZhdGUvdjEvY2FwYWJpbGl0aWVzX3NlcnZpY2UucHJvdG8SD29zYWMucHJpdmF0ZS52MSIYChZDYXBhYmlsaXRpZXNHZXRSZXF1ZXN0IkwKF0NhcGFiaWxpdGllc0dldFJlc3BvbnNlEjEKBWF1dGhuGAEgASgLMiIub3NhYy5wcml2YXRlLnYxLkF1dGhuQ2FwYWJpbGl0aWVzMo4BCgxDYXBhYmlsaXRpZXMSfgoDR2V0Eicub3NhYy5wcml2YXRlLnYxLkNhcGFiaWxpdGllc0dldFJlcXVlc3QaKC5vc2FjLnByaXZhdGUudjEuQ2FwYWJpbGl0aWVzR2V0UmVzcG9uc2UiJILT5JMCHhIcL2FwaS9wcml2YXRlL3YxL2NhcGFiaWxpdGllc0IpirUYJRIOb3NhYy5wdWJsaWMudjEiE3ByaXZhdGU6ZnVsZmlsbG1lbnRiBnByb3RvMw", [file_cleanapi_cleanapi, file_google_api_annotations, file_osac_private_v1_authn_capabilities_type]);

/**
 * Request message for the `Get` method of the `Capabilities` service.
 *
 * @generated from message osac.private.v1.CapabilitiesGetRequest
 */
export type CapabilitiesGetRequest = Message<"osac.private.v1.CapabilitiesGetRequest"> & {
};

/**
 * Describes the message osac.private.v1.CapabilitiesGetRequest.
 * Use `create(CapabilitiesGetRequestSchema)` to create a new message.
 */
export const CapabilitiesGetRequestSchema: GenMessage<CapabilitiesGetRequest> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_capabilities_service, 0);

/**
 * Response message for the `Get` method of the `Capabilities` service.
 *
 * @generated from message osac.private.v1.CapabilitiesGetResponse
 */
export type CapabilitiesGetResponse = Message<"osac.private.v1.CapabilitiesGetResponse"> & {
  /**
   * Authentication capabilities of the server.
   *
   * @generated from field: osac.private.v1.AuthnCapabilities authn = 1;
   */
  authn?: AuthnCapabilities | undefined;
};

/**
 * Describes the message osac.private.v1.CapabilitiesGetResponse.
 * Use `create(CapabilitiesGetResponseSchema)` to create a new message.
 */
export const CapabilitiesGetResponseSchema: GenMessage<CapabilitiesGetResponse> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_capabilities_service, 1);

/**
 * Provides information about the capabilities of the server, such as the list of trusted token issuers for
 * authentication.
 *
 * @generated from service osac.private.v1.Capabilities
 */
export const Capabilities: GenService<{
  /**
   * Returns the capabilities of the server, including the authentication configuration that clients need in order to
   * obtain access tokens.
   *
   * @generated from rpc osac.private.v1.Capabilities.Get
   */
  get: {
    methodKind: "unary";
    input: typeof CapabilitiesGetRequestSchema;
    output: typeof CapabilitiesGetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_private_v1_capabilities_service, 0);
