//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/cluster_template_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import type { Any } from "../../../google/protobuf/any_pb";
import { file_google_protobuf_any } from "../../../google/protobuf/any_pb";
import type { ClusterNetwork } from "./cluster_common_type_pb";
import { file_osac_private_v1_cluster_common_type } from "./cluster_common_type_pb";
import type { ClusterVersionReference } from "./cluster_version_type_pb";
import { file_osac_private_v1_cluster_version_type } from "./cluster_version_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { HostTypeReference } from "./host_type_type_pb";
import { file_osac_private_v1_host_type_type } from "./host_type_type_pb";
import type { SecretLocalReference } from "./secret_type_pb";
import { file_osac_private_v1_secret_type } from "./secret_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/cluster_template_type.proto.
 */
export const file_osac_private_v1_cluster_template_type: GenFile = /*@__PURE__*/
  fileDesc("Citvc2FjL3ByaXZhdGUvdjEvY2x1c3Rlcl90ZW1wbGF0ZV90eXBlLnByb3RvEg9vc2FjLnByaXZhdGUudjEimQMKD0NsdXN0ZXJUZW1wbGF0ZRIKCgJpZBgBIAEoCRIrCghtZXRhZGF0YRgCIAEoCzIZLm9zYWMucHJpdmF0ZS52MS5NZXRhZGF0YRINCgV0aXRsZRgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRJHCgpwYXJhbWV0ZXJzGAUgAygLMjMub3NhYy5wcml2YXRlLnYxLkNsdXN0ZXJUZW1wbGF0ZVBhcmFtZXRlckRlZmluaXRpb24SQQoJbm9kZV9zZXRzGAYgAygLMi4ub3NhYy5wcml2YXRlLnYxLkNsdXN0ZXJUZW1wbGF0ZS5Ob2RlU2V0c0VudHJ5EkMKDXNwZWNfZGVmYXVsdHMYByABKAsyLC5vc2FjLnByaXZhdGUudjEuQ2x1c3RlclRlbXBsYXRlU3BlY0RlZmF1bHRzGlgKDU5vZGVTZXRzRW50cnkSCwoDa2V5GAEgASgJEjYKBXZhbHVlGAIgASgLMicub3NhYy5wcml2YXRlLnYxLkNsdXN0ZXJUZW1wbGF0ZU5vZGVTZXQ6AjgBIp0BCiJDbHVzdGVyVGVtcGxhdGVQYXJhbWV0ZXJEZWZpbml0aW9uEgwKBG5hbWUYASABKAkSDQoFdGl0bGUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSEAoIcmVxdWlyZWQYBCABKAgSDAoEdHlwZRgFIAEoCRIlCgdkZWZhdWx0GAYgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueSJdChZDbHVzdGVyVGVtcGxhdGVOb2RlU2V0EjUKCWhvc3RfdHlwZRgBIAEoCzIiLm9zYWMucHJpdmF0ZS52MS5Ib3N0VHlwZVJlZmVyZW5jZRIMCgRzaXplGAIgASgFIqECChtDbHVzdGVyVGVtcGxhdGVTcGVjRGVmYXVsdHMSGwoOc3NoX3B1YmxpY19rZXkYAiABKAlIAIgBARI1CgduZXR3b3JrGAQgASgLMh8ub3NhYy5wcml2YXRlLnYxLkNsdXN0ZXJOZXR3b3JrSAGIAQESOQoHdmVyc2lvbhgFIAEoCzIoLm9zYWMucHJpdmF0ZS52MS5DbHVzdGVyVmVyc2lvblJlZmVyZW5jZRJBChJwdWxsX3NlY3JldF9zZWNyZXQYBiABKAsyJS5vc2FjLnByaXZhdGUudjEuU2VjcmV0TG9jYWxSZWZlcmVuY2VCEQoPX3NzaF9wdWJsaWNfa2V5QgoKCF9uZXR3b3JrSgQIARACUgtwdWxsX3NlY3JldCJVChhDbHVzdGVyVGVtcGxhdGVSZWZlcmVuY2USCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIPCgdwcm9qZWN0GAMgASgJEg4KBnNoYXJlZBgEIAEoCEIUirUYEBIOb3NhYy5wdWJsaWMudjFiBnByb3RvMw", [file_cleanapi_cleanapi, file_google_protobuf_any, file_osac_private_v1_cluster_common_type, file_osac_private_v1_cluster_version_type, file_osac_private_v1_metadata_type, file_osac_private_v1_host_type_type, file_osac_private_v1_secret_type]);

/**
 * A cluster template defines a type of cluster that can be created by the user. Note that the user doesn't create these
 * templates: the system provides a collection of them, and the user chooses one.
 *
 * buf:lint:ignore OSAC_OBJECT_SHAPE
 *
 * @generated from message osac.private.v1.ClusterTemplate
 */
export type ClusterTemplate = Message<"osac.private.v1.ClusterTemplate"> & {
  /**
   * Unique identifier of the template.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Human friendly short description of the template, only a few words, suitable for displaying in one single line on a
   * UI or CLI.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * Human friendly long description of the template, using Markdown format.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Definitions of the parameters that can be used to customize the template.
   *
   * Note that these are only the *definitions* of the parameters, not the actual values. The actual values are in the
   * `spec.template_parameters` field of the cluster.
   *
   * @generated from field: repeated osac.private.v1.ClusterTemplateParameterDefinition parameters = 5;
   */
  parameters: ClusterTemplateParameterDefinition[];

  /**
   * Initial node sets of the cluster.
   *
   * @generated from field: map<string, osac.private.v1.ClusterTemplateNodeSet> node_sets = 6;
   */
  nodeSets: { [key: string]: ClusterTemplateNodeSet };

  /**
   * Default values for cluster spec fields. When a user creates a cluster
   * without setting these fields, these values are applied.
   *
   * User-provided spec field values always override these defaults.
   *
   * @generated from field: osac.private.v1.ClusterTemplateSpecDefaults spec_defaults = 7;
   */
  specDefaults?: ClusterTemplateSpecDefaults | undefined;
};

/**
 * Describes the message osac.private.v1.ClusterTemplate.
 * Use `create(ClusterTemplateSchema)` to create a new message.
 */
export const ClusterTemplateSchema: GenMessage<ClusterTemplate> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_template_type, 0);

/**
 * Contains type and documentation of a template parameter.
 *
 * @generated from message osac.private.v1.ClusterTemplateParameterDefinition
 */
export type ClusterTemplateParameterDefinition = Message<"osac.private.v1.ClusterTemplateParameterDefinition"> & {
  /**
   * Name of the parameter.
   *
   * This is the name that should be used in the `template_parameters` field of the cluster to assign a value to the
   * parameter.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Human friendly short description of the parameter, only a few words, suitable for displaying in one single line on
   * a UI or CLI.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Human friendly description of the parameter, using Markdown format.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Indicates if this parameter is required or optional.
   *
   * Values for required parameters must be included when creating the cluster, otherwise it will be rejected.
   *
   * Note that there may be other dependencies between parameters which may cause a cluster to be rejected. For example,
   * the allowed values of a parameter may depend on the value of another parameter. That kind of information will be in
   * the `description` field.
   *
   * @generated from field: bool required = 4;
   */
  required: boolean;

  /**
   * Type of the parameter.
   *
   * The possible values are the same as those used by the `type_url` field of the `Any` type:
   *
   * | Type                           | Value                                             |
   * |--------------------------------|---------------------------------------------------|
   * | Boolean                        | `type.googleapis.com/google.protobuf.BoolValue`   |
   * | Integer number, 32 bits        | `type.googleapis.com/google.protobuf.Int32Value`  |
   * | Integer number, 64 bits        | `type.googleapis.com/google.protobuf.Int64Value`  |
   * | Floating point number, 32 bits | `type.googleapis.com/google.protobuf.FloatValue`  |
   * | Floating point number, 64 bits | `type.googleapis.com/google.protobuf.DoubleValue` |
   * | String                         | `type.googleapis.com/google.protobuf.StringValue` |
   * | Timestamp                      | `type.googleapis.com/google.protobuf.Timestamp`   |
   * | Duration                       | `type.googleapis.com/google.protobuf.Duration`    |
   * | Array of bytes                 | `type.googleapis.com/google.protobuf.BytesValue`  |
   * | Any JSON value                 | `type.googleapis.com/google.protobuf.Value`       |
   *
   * When using the HTTP+JSON version of the API the value provided in the `template_parameters` field of the cluster
   * must be represented as documented in the (ProtoJSON format document)[https://protobuf.dev/programming-guides/json].
   *
   * @generated from field: string type = 5;
   */
  type: string;

  /**
   * Default value for optional parameters.
   *
   * @generated from field: google.protobuf.Any default = 6;
   */
  default?: Any | undefined;
};

/**
 * Describes the message osac.private.v1.ClusterTemplateParameterDefinition.
 * Use `create(ClusterTemplateParameterDefinitionSchema)` to create a new message.
 */
export const ClusterTemplateParameterDefinitionSchema: GenMessage<ClusterTemplateParameterDefinition> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_template_type, 1);

/**
 * Defines a set of nodes that will be part of cluster, all of them of the same type of host.
 *
 * @generated from message osac.private.v1.ClusterTemplateNodeSet
 */
export type ClusterTemplateNodeSet = Message<"osac.private.v1.ClusterTemplateNodeSet"> & {
  /**
   * Reference to the type of hosts that are part of the set.
   *
   * @generated from field: osac.private.v1.HostTypeReference host_type = 1;
   */
  hostType?: HostTypeReference | undefined;

  /**
   * Number of nodes of the set.
   *
   * @generated from field: int32 size = 2;
   */
  size: number;
};

/**
 * Describes the message osac.private.v1.ClusterTemplateNodeSet.
 * Use `create(ClusterTemplateNodeSetSchema)` to create a new message.
 */
export const ClusterTemplateNodeSetSchema: GenMessage<ClusterTemplateNodeSet> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_template_type, 2);

/**
 * Default values for cluster spec fields. These are applied when a user creates a cluster without
 * providing explicit values. User-provided values always override these defaults.
 *
 * @generated from message osac.private.v1.ClusterTemplateSpecDefaults
 */
export type ClusterTemplateSpecDefaults = Message<"osac.private.v1.ClusterTemplateSpecDefaults"> & {
  /**
   * Default SSH public key installed on cluster worker nodes.
   *
   * @generated from field: optional string ssh_public_key = 2;
   */
  sshPublicKey?: string | undefined;

  /**
   * Default cluster networking configuration.
   *
   * @generated from field: optional osac.private.v1.ClusterNetwork network = 4;
   */
  network?: ClusterNetwork | undefined;

  /**
   * Default ClusterVersion for clusters created with this template.
   *
   * When set, clusters that don't specify an explicit `spec.version` will use this version. The referenced
   * ClusterVersion must exist, be enabled, and not be in `OBSOLETE` state.
   *
   * @generated from field: osac.private.v1.ClusterVersionReference version = 5;
   */
  version?: ClusterVersionReference | undefined;

  /**
   * Default Secret reference for pull secret credentials.
   *
   * When set, clusters created from this template will use this secret reference unless the user provides an explicit
   * `pull_secret_secret` reference.
   *
   * @generated from field: osac.private.v1.SecretLocalReference pull_secret_secret = 6;
   */
  pullSecretSecret?: SecretLocalReference | undefined;
};

/**
 * Describes the message osac.private.v1.ClusterTemplateSpecDefaults.
 * Use `create(ClusterTemplateSpecDefaultsSchema)` to create a new message.
 */
export const ClusterTemplateSpecDefaultsSchema: GenMessage<ClusterTemplateSpecDefaults> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_template_type, 3);

/**
 * Reference to a ClusterTemplate resource.
 *
 * @generated from message osac.private.v1.ClusterTemplateReference
 */
export type ClusterTemplateReference = Message<"osac.private.v1.ClusterTemplateReference"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string project = 3;
   */
  project: string;

  /**
   * @generated from field: bool shared = 4;
   */
  shared: boolean;
};

/**
 * Describes the message osac.private.v1.ClusterTemplateReference.
 * Use `create(ClusterTemplateReferenceSchema)` to create a new message.
 */
export const ClusterTemplateReferenceSchema: GenMessage<ClusterTemplateReference> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_template_type, 4);
