//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/project_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import type { ConditionStatus } from "./condition_status_type_pb";
import { file_osac_private_v1_condition_status_type } from "./condition_status_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/project_type.proto.
 */
export const file_osac_private_v1_project_type: GenFile = /*@__PURE__*/
  fileDesc("CiJvc2FjL3ByaXZhdGUvdjEvcHJvamVjdF90eXBlLnByb3RvEg9vc2FjLnByaXZhdGUudjEi+wMKB1Byb2plY3QSCgoCaWQYASABKAkSMwoIbWV0YWRhdGEYAiABKAsyGS5vc2FjLnByaXZhdGUudjEuTWV0YWRhdGFCBrpIA9gBAxIqCgRzcGVjGAMgASgLMhwub3NhYy5wcml2YXRlLnYxLlByb2plY3RTcGVjEi4KBnN0YXR1cxgEIAEoCzIeLm9zYWMucHJpdmF0ZS52MS5Qcm9qZWN0U3RhdHVzOtICukjOAhrLAgoVcHJvamVjdF9uYW1lX3NlZ21lbnRzEnxwcm9qZWN0IG5hbWUgbXVzdCBiZSBkb3Qtc2VwYXJhdGVkIEROUyBsYWJlbHMgKGVhY2ggc2VnbWVudDogbWF4IDYzIGNoYXJzLCBsb3dlcmNhc2UgYS16LzAtOS9oeXBoZW4sIGFscGhhbnVtZXJpYyBzdGFydC9lbmQpGrMBdGhpcy5tZXRhZGF0YS5uYW1lLnNpemUoKSA9PSAwIHx8IHRoaXMubWV0YWRhdGEubmFtZS5zcGxpdCgnLicpLmFsbChzZWdtZW50LCBzZWdtZW50LnNpemUoKSA+IDAgJiYgc2VnbWVudC5zaXplKCkgPD0gNjMgJiYgc2VnbWVudC5tYXRjaGVzKCdeW2EtejAtOV0oW2EtejAtOS1dezAsNjF9W2EtejAtOV0pPyQnKSkiRgoLUHJvamVjdFNwZWMSDQoFdGl0bGUYAiABKAkSGAoLZGVzY3JpcHRpb24YAyABKAlIAIgBAUIOCgxfZGVzY3JpcHRpb24ingEKDVByb2plY3RTdGF0dXMSLAoFc3RhdGUYASABKA4yHS5vc2FjLnByaXZhdGUudjEuUHJvamVjdFN0YXRlEhQKB21lc3NhZ2UYAiABKAlIAIgBARI9Cgpjb25kaXRpb25zGAMgAygLMiEub3NhYy5wcml2YXRlLnYxLlByb2plY3RDb25kaXRpb25CBoq1GAIIAUIKCghfbWVzc2FnZSLDAQoQUHJvamVjdENvbmRpdGlvbhIzCgR0eXBlGAEgASgOMiUub3NhYy5wcml2YXRlLnYxLlByb2plY3RDb25kaXRpb25UeXBlEjAKBnN0YXR1cxgCIAEoDjIgLm9zYWMucHJpdmF0ZS52MS5Db25kaXRpb25TdGF0dXMSEwoGcmVhc29uGAMgASgJSACIAQESFAoHbWVzc2FnZRgEIAEoCUgBiAEBOgaKtRgCCAFCCQoHX3JlYXNvbkIKCghfbWVzc2FnZSq5AQoMUHJvamVjdFN0YXRlEh0KGVBST0pFQ1RfU1RBVEVfVU5TUEVDSUZJRUQQABIZChVQUk9KRUNUX1NUQVRFX1BFTkRJTkcQARIYChRQUk9KRUNUX1NUQVRFX0FDVElWRRACEhgKFFBST0pFQ1RfU1RBVEVfRkFJTEVEEAMSGgoWUFJPSkVDVF9TVEFURV9ERUxFVElORxAEEh8KG1BST0pFQ1RfU1RBVEVfREVMRVRFX0ZBSUxFRBAFKpUBChRQcm9qZWN0Q29uZGl0aW9uVHlwZRImCiJQUk9KRUNUX0NPTkRJVElPTl9UWVBFX1VOU1BFQ0lGSUVEEAASIwofUFJPSkVDVF9DT05ESVRJT05fVFlQRV9IVUJfU1lOQxABEigKJFBST0pFQ1RfQ09ORElUSU9OX1RZUEVfS0VZQ0xPQUtfU1lOQxACGgaKtRgCCAFCFIq1GBASDm9zYWMucHVibGljLnYxYgZwcm90bzM", [file_buf_validate_validate, file_cleanapi_cleanapi, file_osac_private_v1_condition_status_type, file_osac_private_v1_metadata_type]);

/**
 * A project is a logical grouping of resources.
 *
 * Projects provide a way to organize and isolate resources, manage access controls, and track resource usage. Projects
 * can be nested to create hierarchical resource organization, allowing for flexible multi-level resource grouping.
 *
 * For nested projects, the parent is identified by the `metadata.project` field, which contains the full name of the
 * parent project. Tenant isolation is enforced via the standard `metadata.tenant` field.
 *
 * Projects support the following use cases:
 * - Organizing resources by team, department, or application
 * - Hierarchical resource isolation (e.g., prod/staging/dev as nested projects)
 * - Quota and resource allocation boundaries
 *
 * @generated from message osac.private.v1.Project
 */
export type Project = Message<"osac.private.v1.Project"> & {
  /**
   * Unique identifier of the project.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the project, including name, labels, finalizers, and timestamps.
   *
   * Project names follow a hierarchical dot-separated DNS label format (e.g., "org.team.project").
   * Each segment must be a valid DNS label: max 63 characters, lowercase letters (a-z), digits (0-9),
   * and hyphens, with alphanumeric start and end.
   *
   * Note: Uses (buf.validate.field).ignore = IGNORE_ALWAYS to skip standard Metadata.name pattern
   * validation (which doesn't allow dots). Project-specific validation is handled by message-level CEL.
   *
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired configuration of the project (user-modifiable).
   *
   * @generated from field: osac.private.v1.ProjectSpec spec = 3;
   */
  spec?: ProjectSpec | undefined;

  /**
   * Current state of the project (system-provided, read-only).
   *
   * @generated from field: osac.private.v1.ProjectStatus status = 4;
   */
  status?: ProjectStatus | undefined;
};

/**
 * Describes the message osac.private.v1.Project.
 * Use `create(ProjectSchema)` to create a new message.
 */
export const ProjectSchema: GenMessage<Project> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_project_type, 0);

/**
 * Defines the desired configuration for a Project.
 *
 * The spec contains user-specified parameters that define how the project should be configured. These fields
 * follow a declarative model where users specify the desired state and the system reconciles to match it.
 *
 * @generated from message osac.private.v1.ProjectSpec
 */
export type ProjectSpec = Message<"osac.private.v1.ProjectSpec"> & {
  /**
   * Human-friendly short description of the project, only a few words, suitable for displaying in one single line on
   * a UI or CLI. For example: "Production Environment" or "Development Workspace".
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Human-friendly long description explaining the purpose or scope of this project. Maximum length: 1024 characters.
   *
   * Example: "Production environment for the customer-facing web application"
   *
   * @generated from field: optional string description = 3;
   */
  description?: string | undefined;
};

/**
 * Describes the message osac.private.v1.ProjectSpec.
 * Use `create(ProjectSpecSchema)` to create a new message.
 */
export const ProjectSpecSchema: GenMessage<ProjectSpec> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_project_type, 1);

/**
 * Represents the current operational state of a Project.
 *
 * Status is system-provided and read-only. Users cannot modify status fields directly; the system updates them
 * based on the reconciliation of the spec.
 *
 * @generated from message osac.private.v1.ProjectStatus
 */
export type ProjectStatus = Message<"osac.private.v1.ProjectStatus"> & {
  /**
   * Current lifecycle state of the project.
   *
   * @generated from field: osac.private.v1.ProjectState state = 1;
   */
  state: ProjectState;

  /**
   * Human-readable message providing additional details about the current state.
   *
   * For PENDING state, this might contain progress information like "Initializing project resources".
   *
   * For FAILED state, contains error details like:
   * - "Circular dependency detected"
   *
   * For ACTIVE state, this is typically empty or contains confirmation like "Project ready for use".
   *
   * For DELETING state, this might contain progress information like "Deleting child projects" or
   * "Cleaning up project resources".
   *
   * For DELETE_FAILED state, contains error details explaining what prevented deletion, such as:
   * - "Failed to delete child projects"
   * - "Resources still attached to project"
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;

  /**
   * Detailed conditions describing the current state of various aspects of the project.
   *
   * Conditions provide fine-grained status information about specific aspects of project initialization,
   * such as whether OpenShift Projects have been created across all hubs, or whether access controls
   * have been configured in Keycloak.
   *
   * Each condition has a type, status (True/False/Unknown), and optional reason and message.
   *
   * @generated from field: repeated osac.private.v1.ProjectCondition conditions = 3;
   */
  conditions: ProjectCondition[];
};

/**
 * Describes the message osac.private.v1.ProjectStatus.
 * Use `create(ProjectStatusSchema)` to create a new message.
 */
export const ProjectStatusSchema: GenMessage<ProjectStatus> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_project_type, 2);

/**
 * Represents a specific aspect of the project's current state.
 *
 * Conditions follow the Kubernetes condition pattern, providing detailed status information
 * about various subsystems or aspects of the project.
 *
 * @generated from message osac.private.v1.ProjectCondition
 */
export type ProjectCondition = Message<"osac.private.v1.ProjectCondition"> & {
  /**
   * Type of condition.
   *
   * @generated from field: osac.private.v1.ProjectConditionType type = 1;
   */
  type: ProjectConditionType;

  /**
   * Status of the condition (True, False, or Unknown).
   *
   * @generated from field: osac.private.v1.ConditionStatus status = 2;
   */
  status: ConditionStatus;

  /**
   * Machine-readable reason for the condition's last transition.
   *
   * This should be a brief CamelCase string that describes why the condition changed.
   * Examples: "HubsSynced", "PartialSync", "SyncFailed"
   *
   * @generated from field: optional string reason = 3;
   */
  reason?: string | undefined;

  /**
   * Human-readable message providing details about the condition.
   *
   * This should explain the current status in more detail, including specifics like
   * which hubs succeeded or failed.
   * Examples:
   * - "OpenShift Projects created on all 5 hubs"
   * - "OpenShift Projects created on 3/5 hubs (failed: hub-east-1, hub-west-2)"
   * - "Failed to sync to any hubs: no hubs available"
   *
   * @generated from field: optional string message = 4;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.private.v1.ProjectCondition.
 * Use `create(ProjectConditionSchema)` to create a new message.
 */
export const ProjectConditionSchema: GenMessage<ProjectCondition> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_project_type, 3);

/**
 * Lifecycle states for Project resources.
 *
 * State transitions typically follow: UNSPECIFIED -> PENDING -> ACTIVE, with FAILED as a terminal error state
 * that may require user intervention or resource recreation. Deletion follows: ACTIVE -> DELETING -> (archived),
 * with DELETE_FAILED as a terminal error state for deletion issues.
 *
 * @generated from enum osac.private.v1.ProjectState
 */
export enum ProjectState {
  /**
   * State is unknown or has not been determined yet. This is the default state before initialization.
   *
   * @generated from enum value: PROJECT_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The project is being initialized and is not ready for use yet.
   *
   * During this state, the system is:
   * - Checking for circular dependencies in the project hierarchy
   * - Initializing project resources and access controls
   *
   * Resources cannot be created in projects in PENDING state.
   *
   * @generated from enum value: PROJECT_STATE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * The project is fully operational and ready for resources.
   *
   * In this state:
   * - Project hierarchy is validated
   * - Access controls are configured
   * - Resources can be created and attached to the project
   *
   * @generated from enum value: PROJECT_STATE_ACTIVE = 2;
   */
  ACTIVE = 2,

  /**
   * The project has encountered an error and is unusable.
   *
   * Common failure reasons include:
   * - Circular dependency detected in project hierarchy
   * - Access control configuration error
   *
   * The status.message field will contain specific error details. Failed projects typically require deletion
   * and recreation with corrected parameters.
   *
   * @generated from enum value: PROJECT_STATE_FAILED = 3;
   */
  FAILED = 3,

  /**
   * The project is being deleted.
   *
   * During this state, the system is:
   * - Deleting or blocking deletion based on child projects
   * - Cleaning up project resources
   * - Removing access controls and permissions
   *
   * The project will be archived once deletion completes successfully.
   *
   * @generated from enum value: PROJECT_STATE_DELETING = 4;
   */
  DELETING = 4,

  /**
   * The project deletion has failed.
   *
   * The deletion operation encountered an error and could not complete.
   * Common failure reasons include:
   * - Failed to delete child projects
   * - Resources still attached to the project
   * - Access control cleanup failure
   *
   * The status.message field will contain specific error details.
   * Manual intervention may be required to resolve the underlying issue
   * before retrying deletion.
   *
   * @generated from enum value: PROJECT_STATE_DELETE_FAILED = 5;
   */
  DELETE_FAILED = 5,
}

/**
 * Describes the enum osac.private.v1.ProjectState.
 */
export const ProjectStateSchema: GenEnum<ProjectState> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_project_type, 0);

/**
 * Types of conditions that can be reported for a Project.
 *
 * @generated from enum osac.private.v1.ProjectConditionType
 */
export enum ProjectConditionType {
  /**
   * Unspecified condition type.
   *
   * @generated from enum value: PROJECT_CONDITION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Indicates whether OpenShift Projects (namespaces) have been successfully created across all managed hubs.
   *
   * Status meanings:
   * - True: OpenShift Projects exist on all hubs
   * - False: OpenShift Projects failed to sync to one or more hubs, or no hubs available
   * - Unknown: Hub sync has not been attempted yet
   *
   * This condition is set during project activation and updated if hubs are added/removed.
   *
   * @generated from enum value: PROJECT_CONDITION_TYPE_HUB_SYNC = 1;
   */
  HUB_SYNC = 1,

  /**
   * Indicates whether Keycloak Authorization Resources have been configured for project-level permissions.
   *
   * Status meanings:
   * - True: Keycloak Authorization Resource created successfully
   * - False: Failed to create Keycloak Authorization Resource
   * - Unknown: Keycloak sync has not been attempted yet
   *
   * This condition is set during project activation.
   *
   * @generated from enum value: PROJECT_CONDITION_TYPE_KEYCLOAK_SYNC = 2;
   */
  KEYCLOAK_SYNC = 2,
}

/**
 * Describes the enum osac.private.v1.ProjectConditionType.
 */
export const ProjectConditionTypeSchema: GenEnum<ProjectConditionType> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_project_type, 1);
