//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/storage_tier_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { StorageProtocol } from "./storage_common_type_pb";
import { file_osac_private_v1_storage_common_type } from "./storage_common_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/storage_tier_type.proto.
 */
export const file_osac_private_v1_storage_tier_type: GenFile = /*@__PURE__*/
  fileDesc("Cidvc2FjL3ByaXZhdGUvdjEvc3RvcmFnZV90aWVyX3R5cGUucHJvdG8SD29zYWMucHJpdmF0ZS52MSKNAQoSQmFja2VuZEFzc29jaWF0aW9uEhIKCmJhY2tlbmRfaWQYASABKAkSHgoWbWF4X3JlYWRfYmFuZHdpZHRoX21icxgCIAEoBRIfChdtYXhfd3JpdGVfYmFuZHdpZHRoX21icxgDIAEoBRIaChJlbmNyeXB0aW9uX2VuYWJsZWQYBCABKAg6Boq1GAIIASKqAQoLU3RvcmFnZVRpZXISCgoCaWQYASABKAkSKwoIbWV0YWRhdGEYAiABKAsyGS5vc2FjLnByaXZhdGUudjEuTWV0YWRhdGESLgoEc3BlYxgDIAEoCzIgLm9zYWMucHJpdmF0ZS52MS5TdG9yYWdlVGllclNwZWMSMgoGc3RhdHVzGAQgASgLMiIub3NhYy5wcml2YXRlLnYxLlN0b3JhZ2VUaWVyU3RhdHVzIoICCg9TdG9yYWdlVGllclNwZWMSEwoLZGVzY3JpcHRpb24YASABKAkSPgoIcHJvdG9jb2wYAiABKA4yIC5vc2FjLnByaXZhdGUudjEuU3RvcmFnZVByb3RvY29sQgq6SAeCAQQQASAAEh4KFm1heF9yZWFkX2JhbmR3aWR0aF9tYnMYAyABKAUSHwoXbWF4X3dyaXRlX2JhbmR3aWR0aF9tYnMYBCABKAUSGgoSZW5jcnlwdGlvbl9lbmFibGVkGAUgASgIEj0KCGJhY2tlbmRzGAYgAygLMiMub3NhYy5wcml2YXRlLnYxLkJhY2tlbmRBc3NvY2lhdGlvbkIGirUYAggBImcKEVN0b3JhZ2VUaWVyU3RhdHVzEjAKBXN0YXRlGAEgASgOMiEub3NhYy5wcml2YXRlLnYxLlN0b3JhZ2VUaWVyU3RhdGUSFAoHbWVzc2FnZRgCIAEoCUgAiAEBQgoKCF9tZXNzYWdlKlUKEFN0b3JhZ2VUaWVyU3RhdGUSIgoeU1RPUkFHRV9USUVSX1NUQVRFX1VOU1BFQ0lGSUVEEAASHQoZU1RPUkFHRV9USUVSX1NUQVRFX0FDVElWRRABQhSKtRgQEg5vc2FjLnB1YmxpYy52MWIGcHJvdG8z", [file_buf_validate_validate, file_cleanapi_cleanapi, file_osac_private_v1_metadata_type, file_osac_private_v1_storage_common_type]);

/**
 * Represents the association of a storage backend within a storage tier, including bandwidth and
 * encryption configuration.
 *
 * @generated from message osac.private.v1.BackendAssociation
 */
export type BackendAssociation = Message<"osac.private.v1.BackendAssociation"> & {
  /**
   * Unique identifier of the associated storage backend.
   *
   * @generated from field: string backend_id = 1;
   */
  backendId: string;

  /**
   * Maximum read bandwidth in megabytes per second.
   *
   * @generated from field: int32 max_read_bandwidth_mbs = 2;
   */
  maxReadBandwidthMbs: number;

  /**
   * Maximum write bandwidth in megabytes per second.
   *
   * @generated from field: int32 max_write_bandwidth_mbs = 3;
   */
  maxWriteBandwidthMbs: number;

  /**
   * Whether data at rest is encrypted on this backend.
   *
   * @generated from field: bool encryption_enabled = 4;
   */
  encryptionEnabled: boolean;
};

/**
 * Describes the message osac.private.v1.BackendAssociation.
 * Use `create(BackendAssociationSchema)` to create a new message.
 */
export const BackendAssociationSchema: GenMessage<BackendAssociation> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_storage_tier_type, 0);

/**
 * Describes a class of storage service that can be referenced by name when provisioning
 * storage-enabled resources.
 *
 * StorageTiers are admin-managed catalog resources. Tenant users select a tier by name instead of
 * specifying raw storage backend details. Cloud Provider Admins control the available tiers through
 * the private API.
 *
 * The `spec` contains the tier's advertised service level. The `status` contains the current state
 * of the storage tier, is provided by the system and can't be modified by the user.
 *
 * @generated from message osac.private.v1.StorageTier
 */
export type StorageTier = Message<"osac.private.v1.StorageTier"> & {
  /**
   * Unique identifier of the storage tier.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the storage tier.
   *
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Advertised service level of the storage tier.
   *
   * @generated from field: osac.private.v1.StorageTierSpec spec = 3;
   */
  spec?: StorageTierSpec | undefined;

  /**
   * Current operational status of the storage tier.
   *
   * @generated from field: osac.private.v1.StorageTierStatus status = 4;
   */
  status?: StorageTierStatus | undefined;
};

/**
 * Describes the message osac.private.v1.StorageTier.
 * Use `create(StorageTierSchema)` to create a new message.
 */
export const StorageTierSchema: GenMessage<StorageTier> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_storage_tier_type, 1);

/**
 * Defines the advertised service level of a StorageTier.
 *
 * @generated from message osac.private.v1.StorageTierSpec
 */
export type StorageTierSpec = Message<"osac.private.v1.StorageTierSpec"> & {
  /**
   * Human-readable description of the storage tier.
   *
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * Storage protocol used by this tier. Always an explicit protocol (NFS or BLOCK); never UNSPECIFIED.
   *
   * @generated from field: osac.private.v1.StorageProtocol protocol = 2;
   */
  protocol: StorageProtocol;

  /**
   * Maximum read bandwidth in megabytes per second.
   *
   * @generated from field: int32 max_read_bandwidth_mbs = 3;
   */
  maxReadBandwidthMbs: number;

  /**
   * Maximum write bandwidth in megabytes per second.
   *
   * @generated from field: int32 max_write_bandwidth_mbs = 4;
   */
  maxWriteBandwidthMbs: number;

  /**
   * Whether data at rest is encrypted on this tier.
   *
   * @generated from field: bool encryption_enabled = 5;
   */
  encryptionEnabled: boolean;

  /**
   * List of backend associations that compose this storage tier.
   *
   * @generated from field: repeated osac.private.v1.BackendAssociation backends = 6;
   */
  backends: BackendAssociation[];
};

/**
 * Describes the message osac.private.v1.StorageTierSpec.
 * Use `create(StorageTierSpecSchema)` to create a new message.
 */
export const StorageTierSpecSchema: GenMessage<StorageTierSpec> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_storage_tier_type, 2);

/**
 * Contains the system-provided status of a StorageTier.
 *
 * @generated from message osac.private.v1.StorageTierStatus
 */
export type StorageTierStatus = Message<"osac.private.v1.StorageTierStatus"> & {
  /**
   * Current lifecycle state of the storage tier.
   *
   * @generated from field: osac.private.v1.StorageTierState state = 1;
   */
  state: StorageTierState;

  /**
   * Human-readable message providing additional details about the current state.
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.private.v1.StorageTierStatus.
 * Use `create(StorageTierStatusSchema)` to create a new message.
 */
export const StorageTierStatusSchema: GenMessage<StorageTierStatus> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_storage_tier_type, 3);

/**
 * Lifecycle states for StorageTier resources.
 *
 * @generated from enum osac.private.v1.StorageTierState
 */
export enum StorageTierState {
  /**
   * State is unknown or has not been determined yet.
   *
   * @generated from enum value: STORAGE_TIER_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The storage tier is active and available for use by tenants.
   *
   * @generated from enum value: STORAGE_TIER_STATE_ACTIVE = 1;
   */
  ACTIVE = 1,
}

/**
 * Describes the enum osac.private.v1.StorageTierState.
 */
export const StorageTierStateSchema: GenEnum<StorageTierState> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_storage_tier_type, 0);
