//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/volume_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { StorageProtocol } from "./storage_common_type_pb";
import { file_osac_private_v1_storage_common_type } from "./storage_common_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/volume_type.proto.
 */
export const file_osac_private_v1_volume_type: GenFile = /*@__PURE__*/
  fileDesc("CiFvc2FjL3ByaXZhdGUvdjEvdm9sdW1lX3R5cGUucHJvdG8SD29zYWMucHJpdmF0ZS52MSKbAQoGVm9sdW1lEgoKAmlkGAEgASgJEisKCG1ldGFkYXRhGAIgASgLMhkub3NhYy5wcml2YXRlLnYxLk1ldGFkYXRhEikKBHNwZWMYAyABKAsyGy5vc2FjLnByaXZhdGUudjEuVm9sdW1lU3BlYxItCgZzdGF0dXMYBCABKAsyHS5vc2FjLnByaXZhdGUudjEuVm9sdW1lU3RhdHVzIogBCgpWb2x1bWVTcGVjEh0KDHN0b3JhZ2VfdGllchgBIAEoCUIHukgEcgIQARIZCghzaXplX2dpYhgCIAEoA0IHukgEIgIgABJACgthY2Nlc3NfbW9kZRgDIAEoDjIhLm9zYWMucHJpdmF0ZS52MS5Wb2x1bWVBY2Nlc3NNb2RlQgi6SAWCAQIQASLJAgoMVm9sdW1lU3RhdHVzEisKBXN0YXRlGAEgASgOMhwub3NhYy5wcml2YXRlLnYxLlZvbHVtZVN0YXRlEhQKB21lc3NhZ2UYAiABKAlIAIgBARIYChB2ZW5kb3Jfdm9sdW1lX2lkGAMgASgJEg8KB2JhY2tlbmQYBCABKAkSMgoIcHJvdG9jb2wYBSABKA4yIC5vc2FjLnByaXZhdGUudjEuU3RvcmFnZVByb3RvY29sEgsKA2h1YhgGIAEoCRJICg52ZW5kb3JfY29udGV4dBgHIAMoCzIwLm9zYWMucHJpdmF0ZS52MS5Wb2x1bWVTdGF0dXMuVmVuZG9yQ29udGV4dEVudHJ5GjQKElZlbmRvckNvbnRleHRFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQgoKCF9tZXNzYWdlKtkBChBWb2x1bWVBY2Nlc3NNb2RlEiIKHlZPTFVNRV9BQ0NFU1NfTU9ERV9VTlNQRUNJRklFRBAAEiYKIlZPTFVNRV9BQ0NFU1NfTU9ERV9SRUFEX1dSSVRFX09OQ0UQARIlCiFWT0xVTUVfQUNDRVNTX01PREVfUkVBRF9PTkxZX01BTlkQAhImCiJWT0xVTUVfQUNDRVNTX01PREVfUkVBRF9XUklURV9NQU5ZEAMSKgomVk9MVU1FX0FDQ0VTU19NT0RFX1JFQURfV1JJVEVfT05DRV9QT0QQBCqwAQoLVm9sdW1lU3RhdGUSHAoYVk9MVU1FX1NUQVRFX1VOU1BFQ0lGSUVEEAASGQoVVk9MVU1FX1NUQVRFX0NSRUFUSU5HEAESGgoWVk9MVU1FX1NUQVRFX0FWQUlMQUJMRRACEhcKE1ZPTFVNRV9TVEFURV9GQUlMRUQQAxIZChVWT0xVTUVfU1RBVEVfREVMRVRJTkcQBBIYChRWT0xVTUVfU1RBVEVfREVMRVRFRBAFQgaKtRgCCAFiBnByb3RvMw", [file_buf_validate_validate, file_cleanapi_cleanapi, file_osac_private_v1_metadata_type, file_osac_private_v1_storage_common_type]);

/**
 * Represents a block storage volume managed by the OSAC storage control plane.
 *
 * Volumes are tenant-scoped resources that represent storage provisioned on a backend storage array
 * through the OSAC CSI driver. The fulfillment-service tracks volume inventory in PostgreSQL and
 * reconciles Volume CRs on the hub cluster. The osac-operator Volume controller handles vendor
 * provisioning via the backend's CSI controller.
 *
 * Volumes are created through the private API, typically by the OSAC CSI driver in response to a
 * PVC on a tenant cluster. The spec captures the user's requested configuration (tier, size,
 * access mode), while the status tracks the system-resolved state (vendor volume ID, backend,
 * protocol).
 *
 * @generated from message osac.private.v1.Volume
 */
export type Volume = Message<"osac.private.v1.Volume"> & {
  /**
   * Unique identifier of the volume.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the volume.
   *
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired configuration of the volume (immutable after creation).
   *
   * @generated from field: osac.private.v1.VolumeSpec spec = 3;
   */
  spec?: VolumeSpec | undefined;

  /**
   * Current operational status of the volume.
   *
   * @generated from field: osac.private.v1.VolumeStatus status = 4;
   */
  status?: VolumeStatus | undefined;
};

/**
 * Describes the message osac.private.v1.Volume.
 * Use `create(VolumeSchema)` to create a new message.
 */
export const VolumeSchema: GenMessage<Volume> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_volume_type, 0);

/**
 * Defines the desired configuration for a Volume. All fields are immutable after creation.
 *
 * @generated from message osac.private.v1.VolumeSpec
 */
export type VolumeSpec = Message<"osac.private.v1.VolumeSpec"> & {
  /**
   * Name of the StorageTier that determines which backend and protocol serve this volume.
   *
   * @generated from field: string storage_tier = 1;
   */
  storageTier: string;

  /**
   * Requested storage capacity in gibibytes (GiB).
   *
   * @generated from field: int64 size_gib = 2;
   */
  sizeGib: bigint;

  /**
   * Kubernetes access mode for the volume.
   *
   * @generated from field: osac.private.v1.VolumeAccessMode access_mode = 3;
   */
  accessMode: VolumeAccessMode;
};

/**
 * Describes the message osac.private.v1.VolumeSpec.
 * Use `create(VolumeSpecSchema)` to create a new message.
 */
export const VolumeSpecSchema: GenMessage<VolumeSpec> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_volume_type, 1);

/**
 * Represents the current operational state of a Volume.
 *
 * @generated from message osac.private.v1.VolumeStatus
 */
export type VolumeStatus = Message<"osac.private.v1.VolumeStatus"> & {
  /**
   * Current lifecycle state of the volume.
   *
   * @generated from field: osac.private.v1.VolumeState state = 1;
   */
  state: VolumeState;

  /**
   * Human-readable message providing additional details about the current state.
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;

  /**
   * Opaque identifier assigned by the vendor storage array. Set by the osac-operator after vendor
   * CSI CreateVolume succeeds.
   *
   * @generated from field: string vendor_volume_id = 3;
   */
  vendorVolumeId: string;

  /**
   * Name of the StorageBackend that serves this volume. Resolved during tier resolution at
   * creation time. Visible only through the private API.
   *
   * @generated from field: string backend = 4;
   */
  backend: string;

  /**
   * Storage protocol used for this volume. Resolved during tier resolution at creation time.
   * Visible only through the private API.
   *
   * @generated from field: osac.private.v1.StorageProtocol protocol = 5;
   */
  protocol: StorageProtocol;

  /**
   * Identifier of the hub cluster where the Volume CR is created. Set by the fulfillment-service
   * reconciler when selecting the hub. Used to look up the hub connection during delete.
   *
   * @generated from field: string hub = 6;
   */
  hub: string;

  /**
   * Backend-specific attach parameters needed by the vendor CSI controller (for example VAST's
   * "subsystem" and "vip_pool_name"). Opaque to fulfillment-service and osac-csi-driver: set by
   * the osac-operator from the same parameters it used for the vendor CreateVolume call, and
   * forwarded unchanged by osac-csi-driver to the vendor CSI controller's ControllerPublishVolume.
   *
   * @generated from field: map<string, string> vendor_context = 7;
   */
  vendorContext: { [key: string]: string };
};

/**
 * Describes the message osac.private.v1.VolumeStatus.
 * Use `create(VolumeStatusSchema)` to create a new message.
 */
export const VolumeStatusSchema: GenMessage<VolumeStatus> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_volume_type, 2);

/**
 * Access modes for Volume resources, matching Kubernetes PersistentVolume access modes.
 * https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
 *
 * @generated from enum osac.private.v1.VolumeAccessMode
 */
export enum VolumeAccessMode {
  /**
   * Access mode is unknown or has not been specified.
   *
   * @generated from enum value: VOLUME_ACCESS_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The volume can be mounted as read-write by a single node.
   *
   * @generated from enum value: VOLUME_ACCESS_MODE_READ_WRITE_ONCE = 1;
   */
  READ_WRITE_ONCE = 1,

  /**
   * The volume can be mounted as read-only by many nodes.
   *
   * @generated from enum value: VOLUME_ACCESS_MODE_READ_ONLY_MANY = 2;
   */
  READ_ONLY_MANY = 2,

  /**
   * The volume can be mounted as read-write by many nodes.
   *
   * @generated from enum value: VOLUME_ACCESS_MODE_READ_WRITE_MANY = 3;
   */
  READ_WRITE_MANY = 3,

  /**
   * The volume can be mounted as read-write by a single pod (requires CSI 1.5+).
   *
   * @generated from enum value: VOLUME_ACCESS_MODE_READ_WRITE_ONCE_POD = 4;
   */
  READ_WRITE_ONCE_POD = 4,
}

/**
 * Describes the enum osac.private.v1.VolumeAccessMode.
 */
export const VolumeAccessModeSchema: GenEnum<VolumeAccessMode> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_volume_type, 0);

/**
 * Lifecycle states for Volume resources.
 *
 * @generated from enum osac.private.v1.VolumeState
 */
export enum VolumeState {
  /**
   * State is unknown or has not been determined yet.
   *
   * @generated from enum value: VOLUME_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The volume is being provisioned on the storage backend.
   *
   * @generated from enum value: VOLUME_STATE_CREATING = 1;
   */
  CREATING = 1,

  /**
   * The volume has been provisioned and is ready for use.
   *
   * @generated from enum value: VOLUME_STATE_AVAILABLE = 2;
   */
  AVAILABLE = 2,

  /**
   * The volume provisioning has permanently failed after max retries and requires admin intervention.
   *
   * @generated from enum value: VOLUME_STATE_FAILED = 3;
   */
  FAILED = 3,

  /**
   * The volume is being deprovisioned from the storage backend.
   *
   * @generated from enum value: VOLUME_STATE_DELETING = 4;
   */
  DELETING = 4,

  /**
   * The volume has been fully deprovisioned and the record is archived.
   *
   * @generated from enum value: VOLUME_STATE_DELETED = 5;
   */
  DELETED = 5,
}

/**
 * Describes the enum osac.private.v1.VolumeState.
 */
export const VolumeStateSchema: GenEnum<VolumeState> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_volume_type, 1);
