{{- if not .Values.consoleProxy.disabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osac-operator.fullname" . }}-console-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-operator.consoleProxy.labels" . | nindent 4 }}
{{- end }}
