//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/baremetal_instance_types_service.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { BareMetalInstanceType } from "./baremetal_instance_type_type_pb";
import { file_osac_public_v1_baremetal_instance_type_type } from "./baremetal_instance_type_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/baremetal_instance_types_service.proto.
 */
export const file_osac_public_v1_baremetal_instance_types_service: GenFile = /*@__PURE__*/
  fileDesc("CjVvc2FjL3B1YmxpYy92MS9iYXJlbWV0YWxfaW5zdGFuY2VfdHlwZXNfc2VydmljZS5wcm90bxIOb3NhYy5wdWJsaWMudjEinwEKIUJhcmVNZXRhbEluc3RhbmNlVHlwZXNMaXN0UmVxdWVzdBITCgZvZmZzZXQYASABKAVIAIgBARISCgVsaW1pdBgCIAEoBUgBiAEBEhMKBmZpbHRlchgDIAEoCUgCiAEBEhIKBW9yZGVyGAQgASgJSAOIAQFCCQoHX29mZnNldEIICgZfbGltaXRCCQoHX2ZpbHRlckIICgZfb3JkZXIidwoiQmFyZU1ldGFsSW5zdGFuY2VUeXBlc0xpc3RSZXNwb25zZRIMCgRzaXplGAEgASgFEg0KBXRvdGFsGAIgASgFEjQKBWl0ZW1zGAMgAygLMiUub3NhYy5wdWJsaWMudjEuQmFyZU1ldGFsSW5zdGFuY2VUeXBlIi4KIEJhcmVNZXRhbEluc3RhbmNlVHlwZXNHZXRSZXF1ZXN0EgoKAmlkGAEgASgJIloKIUJhcmVNZXRhbEluc3RhbmNlVHlwZXNHZXRSZXNwb25zZRI1CgZvYmplY3QYASABKAsyJS5vc2FjLnB1YmxpYy52MS5CYXJlTWV0YWxJbnN0YW5jZVR5cGUy8AIKFkJhcmVNZXRhbEluc3RhbmNlVHlwZXMSpAEKBExpc3QSMS5vc2FjLnB1YmxpYy52MS5CYXJlTWV0YWxJbnN0YW5jZVR5cGVzTGlzdFJlcXVlc3QaMi5vc2FjLnB1YmxpYy52MS5CYXJlTWV0YWxJbnN0YW5jZVR5cGVzTGlzdFJlc3BvbnNlIjWC0+STAi8SLS9hcGkvZnVsZmlsbG1lbnQvdjEvYmFyZV9tZXRhbF9pbnN0YW5jZV90eXBlcxKuAQoDR2V0EjAub3NhYy5wdWJsaWMudjEuQmFyZU1ldGFsSW5zdGFuY2VUeXBlc0dldFJlcXVlc3QaMS5vc2FjLnB1YmxpYy52MS5CYXJlTWV0YWxJbnN0YW5jZVR5cGVzR2V0UmVzcG9uc2UiQoLT5JMCPGIGb2JqZWN0EjIvYXBpL2Z1bGZpbGxtZW50L3YxL2JhcmVfbWV0YWxfaW5zdGFuY2VfdHlwZXMve2lkfWIGcHJvdG8z", [file_google_api_annotations, file_osac_public_v1_baremetal_instance_type_type]);

/**
 * @generated from message osac.public.v1.BareMetalInstanceTypesListRequest
 */
export type BareMetalInstanceTypesListRequest = Message<"osac.public.v1.BareMetalInstanceTypesListRequest"> & {
  /**
   * Index of the first result. If not specified the default value will be zero.
   *
   * @generated from field: optional int32 offset = 1;
   */
  offset?: number | undefined;

  /**
   * Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
   * that there may not be enough results to return, and that the server may decide, for performance reasons, to return
   * less results than requested.
   *
   * @generated from field: optional int32 limit = 2;
   */
  limit?: number | undefined;

  /**
   * Filter criteria.
   *
   * The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
   * built-in `this` variable refers to the object being tested and `now` refers to the current date and time. If the
   * expression evaluates to `true` the object is included in the results. For example, to retrieve all bare metal
   * instance types with names starting with `gpu`:
   *
   *     this.metadata.name.startsWith("gpu")
   *
   * If this isn't provided, or if the value is empty, then all the bare metal instance types that the user has
   * permission to see will be returned. Not all CEL constructs are currently supported for implementation reasons; see
   * the filter documentation (docs/FILTER.md) for the full details.
   *
   * @generated from field: optional string filter = 3;
   */
  filter?: string | undefined;

  /**
   * Order criteria.
   *
   * The syntax of this parameter is similar to the syntax of the _order by_ clause of a SQL statement, but using the
   * names of the attributes of the bare metal instance type instead of the names of the columns of a table. For
   * example, in order to sort the bare metal instance types descending by name the value should be:
   *
   *     name desc
   *
   * If the parameter isn't provided, or if the value is empty, then the order of the results is undefined.
   *
   * @generated from field: optional string order = 4;
   */
  order?: string | undefined;
};

/**
 * Describes the message osac.public.v1.BareMetalInstanceTypesListRequest.
 * Use `create(BareMetalInstanceTypesListRequestSchema)` to create a new message.
 */
export const BareMetalInstanceTypesListRequestSchema: GenMessage<BareMetalInstanceTypesListRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_baremetal_instance_types_service, 0);

/**
 * @generated from message osac.public.v1.BareMetalInstanceTypesListResponse
 */
export type BareMetalInstanceTypesListResponse = Message<"osac.public.v1.BareMetalInstanceTypesListResponse"> & {
  /**
   * Actual number of items returned. Note that this may be smaller than the value requested in the `limit` parameter
   * of the request if there are not enough items, or of the system decides that returning that number of items isn't
   * feasible or convenient for performance reasons.
   *
   * @generated from field: int32 size = 1;
   */
  size: number;

  /**
   * Total number of items of the collection that match the search criteria, regardless of the number of results
   * requested with the `limit` parameter.
   *
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * List of results.
   *
   * @generated from field: repeated osac.public.v1.BareMetalInstanceType items = 3;
   */
  items: BareMetalInstanceType[];
};

/**
 * Describes the message osac.public.v1.BareMetalInstanceTypesListResponse.
 * Use `create(BareMetalInstanceTypesListResponseSchema)` to create a new message.
 */
export const BareMetalInstanceTypesListResponseSchema: GenMessage<BareMetalInstanceTypesListResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_baremetal_instance_types_service, 1);

/**
 * @generated from message osac.public.v1.BareMetalInstanceTypesGetRequest
 */
export type BareMetalInstanceTypesGetRequest = Message<"osac.public.v1.BareMetalInstanceTypesGetRequest"> & {
  /**
   * Unique identifier of the bare metal instance type.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message osac.public.v1.BareMetalInstanceTypesGetRequest.
 * Use `create(BareMetalInstanceTypesGetRequestSchema)` to create a new message.
 */
export const BareMetalInstanceTypesGetRequestSchema: GenMessage<BareMetalInstanceTypesGetRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_baremetal_instance_types_service, 2);

/**
 * @generated from message osac.public.v1.BareMetalInstanceTypesGetResponse
 */
export type BareMetalInstanceTypesGetResponse = Message<"osac.public.v1.BareMetalInstanceTypesGetResponse"> & {
  /**
   * @generated from field: osac.public.v1.BareMetalInstanceType object = 1;
   */
  object?: BareMetalInstanceType | undefined;
};

/**
 * Describes the message osac.public.v1.BareMetalInstanceTypesGetResponse.
 * Use `create(BareMetalInstanceTypesGetResponseSchema)` to create a new message.
 */
export const BareMetalInstanceTypesGetResponseSchema: GenMessage<BareMetalInstanceTypesGetResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_baremetal_instance_types_service, 3);

/**
 * @generated from service osac.public.v1.BareMetalInstanceTypes
 */
export const BareMetalInstanceTypes: GenService<{
  /**
   * Retrieves the list of bare metal instance types.
   *
   * @generated from rpc osac.public.v1.BareMetalInstanceTypes.List
   */
  list: {
    methodKind: "unary";
    input: typeof BareMetalInstanceTypesListRequestSchema;
    output: typeof BareMetalInstanceTypesListResponseSchema;
  },
  /**
   * Retrieves the details of one specific bare metal instance type.
   *
   * @generated from rpc osac.public.v1.BareMetalInstanceTypes.Get
   */
  get: {
    methodKind: "unary";
    input: typeof BareMetalInstanceTypesGetRequestSchema;
    output: typeof BareMetalInstanceTypesGetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_public_v1_baremetal_instance_types_service, 0);
