//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/external_ip_pools_service.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { ExternalIPPool } from "./external_ip_pool_type_pb";
import { file_osac_public_v1_external_ip_pool_type } from "./external_ip_pool_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/external_ip_pools_service.proto.
 */
export const file_osac_public_v1_external_ip_pools_service: GenFile = /*@__PURE__*/
  fileDesc("Ci5vc2FjL3B1YmxpYy92MS9leHRlcm5hbF9pcF9wb29sc19zZXJ2aWNlLnByb3RvEg5vc2FjLnB1YmxpYy52MSJ6ChpFeHRlcm5hbElQUG9vbHNMaXN0UmVxdWVzdBITCgZvZmZzZXQYASABKAVIAIgBARISCgVsaW1pdBgCIAEoBUgBiAEBEhMKBmZpbHRlchgDIAEoCUgCiAEBQgkKB19vZmZzZXRCCAoGX2xpbWl0QgkKB19maWx0ZXIiaQobRXh0ZXJuYWxJUFBvb2xzTGlzdFJlc3BvbnNlEgwKBHNpemUYASABKAUSDQoFdG90YWwYAiABKAUSLQoFaXRlbXMYAyADKAsyHi5vc2FjLnB1YmxpYy52MS5FeHRlcm5hbElQUG9vbCInChlFeHRlcm5hbElQUG9vbHNHZXRSZXF1ZXN0EgoKAmlkGAEgASgJIkwKGkV4dGVybmFsSVBQb29sc0dldFJlc3BvbnNlEi4KBm9iamVjdBgBIAEoCzIeLm9zYWMucHVibGljLnYxLkV4dGVybmFsSVBQb29sMr0CCg9FeHRlcm5hbElQUG9vbHMSjgEKBExpc3QSKi5vc2FjLnB1YmxpYy52MS5FeHRlcm5hbElQUG9vbHNMaXN0UmVxdWVzdBorLm9zYWMucHVibGljLnYxLkV4dGVybmFsSVBQb29sc0xpc3RSZXNwb25zZSItgtPkkwInEiUvYXBpL2Z1bGZpbGxtZW50L3YxL2V4dGVybmFsX2lwX3Bvb2xzEpgBCgNHZXQSKS5vc2FjLnB1YmxpYy52MS5FeHRlcm5hbElQUG9vbHNHZXRSZXF1ZXN0Gioub3NhYy5wdWJsaWMudjEuRXh0ZXJuYWxJUFBvb2xzR2V0UmVzcG9uc2UiOoLT5JMCNGIGb2JqZWN0EiovYXBpL2Z1bGZpbGxtZW50L3YxL2V4dGVybmFsX2lwX3Bvb2xzL3tpZH1iBnByb3RvMw", [file_google_api_annotations, file_osac_public_v1_external_ip_pool_type]);

/**
 * @generated from message osac.public.v1.ExternalIPPoolsListRequest
 */
export type ExternalIPPoolsListRequest = Message<"osac.public.v1.ExternalIPPoolsListRequest"> & {
  /**
   * Index of the first result. If not specified the default value will be zero.
   *
   * @generated from field: optional int32 offset = 1;
   */
  offset?: number | undefined;

  /**
   * Maximum number of results to be returned by the server. When not specified all the results will be returned.
   *
   * @generated from field: optional int32 limit = 2;
   */
  limit?: number | undefined;

  /**
   * Filter criteria.
   *
   * The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
   * built-in `this` variable refers to the object being tested and `now` refers to the current date and time. If the
   * expression evaluates to `true` the object is included in the results. For example, to retrieve all IPv4 external
   * IP pools:
   *
   *     this.spec.ip_family == IP_FAMILY_IPV4
   *
   * If this isn't provided, or if the value is empty, then all pools visible to the user are returned.
   *
   * @generated from field: optional string filter = 3;
   */
  filter?: string | undefined;
};

/**
 * Describes the message osac.public.v1.ExternalIPPoolsListRequest.
 * Use `create(ExternalIPPoolsListRequestSchema)` to create a new message.
 */
export const ExternalIPPoolsListRequestSchema: GenMessage<ExternalIPPoolsListRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_external_ip_pools_service, 0);

/**
 * @generated from message osac.public.v1.ExternalIPPoolsListResponse
 */
export type ExternalIPPoolsListResponse = Message<"osac.public.v1.ExternalIPPoolsListResponse"> & {
  /**
   * Actual number of items returned.
   *
   * @generated from field: int32 size = 1;
   */
  size: number;

  /**
   * Total number of items matching the search criteria.
   *
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * List of results.
   *
   * @generated from field: repeated osac.public.v1.ExternalIPPool items = 3;
   */
  items: ExternalIPPool[];
};

/**
 * Describes the message osac.public.v1.ExternalIPPoolsListResponse.
 * Use `create(ExternalIPPoolsListResponseSchema)` to create a new message.
 */
export const ExternalIPPoolsListResponseSchema: GenMessage<ExternalIPPoolsListResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_external_ip_pools_service, 1);

/**
 * @generated from message osac.public.v1.ExternalIPPoolsGetRequest
 */
export type ExternalIPPoolsGetRequest = Message<"osac.public.v1.ExternalIPPoolsGetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message osac.public.v1.ExternalIPPoolsGetRequest.
 * Use `create(ExternalIPPoolsGetRequestSchema)` to create a new message.
 */
export const ExternalIPPoolsGetRequestSchema: GenMessage<ExternalIPPoolsGetRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_external_ip_pools_service, 2);

/**
 * @generated from message osac.public.v1.ExternalIPPoolsGetResponse
 */
export type ExternalIPPoolsGetResponse = Message<"osac.public.v1.ExternalIPPoolsGetResponse"> & {
  /**
   * @generated from field: osac.public.v1.ExternalIPPool object = 1;
   */
  object?: ExternalIPPool | undefined;
};

/**
 * Describes the message osac.public.v1.ExternalIPPoolsGetResponse.
 * Use `create(ExternalIPPoolsGetResponseSchema)` to create a new message.
 */
export const ExternalIPPoolsGetResponseSchema: GenMessage<ExternalIPPoolsGetResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_external_ip_pools_service, 3);

/**
 * @generated from service osac.public.v1.ExternalIPPools
 */
export const ExternalIPPools: GenService<{
  /**
   * Retrieves the list of external IP pools visible to the caller.
   *
   * @generated from rpc osac.public.v1.ExternalIPPools.List
   */
  list: {
    methodKind: "unary";
    input: typeof ExternalIPPoolsListRequestSchema;
    output: typeof ExternalIPPoolsListResponseSchema;
  },
  /**
   * Retrieves the details of one specific external IP pool.
   *
   * @generated from rpc osac.public.v1.ExternalIPPools.Get
   */
  get: {
    methodKind: "unary";
    input: typeof ExternalIPPoolsGetRequestSchema;
    output: typeof ExternalIPPoolsGetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_public_v1_external_ip_pools_service, 0);
