//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/external_ip_attachment_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { BareMetalInstanceLocalReference } from "./baremetal_instance_type_pb";
import { file_osac_public_v1_baremetal_instance_type } from "./baremetal_instance_type_pb";
import type { ClusterLocalReference } from "./cluster_type_pb";
import { file_osac_public_v1_cluster_type } from "./cluster_type_pb";
import type { ComputeInstanceLocalReference } from "./compute_instance_type_pb";
import { file_osac_public_v1_compute_instance_type } from "./compute_instance_type_pb";
import type { ExternalIPLocalReference } from "./external_ip_type_pb";
import { file_osac_public_v1_external_ip_type } from "./external_ip_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/external_ip_attachment_type.proto.
 */
export const file_osac_public_v1_external_ip_attachment_type: GenFile = /*@__PURE__*/
  fileDesc("CjBvc2FjL3B1YmxpYy92MS9leHRlcm5hbF9pcF9hdHRhY2htZW50X3R5cGUucHJvdG8SDm9zYWMucHVibGljLnYxIsIBChRFeHRlcm5hbElQQXR0YWNobWVudBIKCgJpZBgBIAEoCRIqCghtZXRhZGF0YRgCIAEoCzIYLm9zYWMucHVibGljLnYxLk1ldGFkYXRhEjYKBHNwZWMYAyABKAsyKC5vc2FjLnB1YmxpYy52MS5FeHRlcm5hbElQQXR0YWNobWVudFNwZWMSOgoGc3RhdHVzGAQgASgLMioub3NhYy5wdWJsaWMudjEuRXh0ZXJuYWxJUEF0dGFjaG1lbnRTdGF0dXMiiwMKGEV4dGVybmFsSVBBdHRhY2htZW50U3BlYxJFCgtleHRlcm5hbF9pcBgBIAEoCzIoLm9zYWMucHVibGljLnYxLkV4dGVybmFsSVBMb2NhbFJlZmVyZW5jZUIG4EEC4EEFEkkKEGNvbXB1dGVfaW5zdGFuY2UYAiABKAsyLS5vc2FjLnB1YmxpYy52MS5Db21wdXRlSW5zdGFuY2VMb2NhbFJlZmVyZW5jZUgAEjgKB2NsdXN0ZXIYAyABKAsyJS5vc2FjLnB1YmxpYy52MS5DbHVzdGVyTG9jYWxSZWZlcmVuY2VIABJNChJiYXJlbWV0YWxfaW5zdGFuY2UYBCABKAsyLy5vc2FjLnB1YmxpYy52MS5CYXJlTWV0YWxJbnN0YW5jZUxvY2FsUmVmZXJlbmNlSAASSgoPdGFyZ2V0X2VuZHBvaW50GAUgASgOMiwub3NhYy5wdWJsaWMudjEuRXh0ZXJuYWxJUEF0dGFjaG1lbnRFbmRwb2ludEID4EEFQggKBnRhcmdldCKkAQoaRXh0ZXJuYWxJUEF0dGFjaG1lbnRTdGF0dXMSPQoFc3RhdGUYASABKA4yKS5vc2FjLnB1YmxpYy52MS5FeHRlcm5hbElQQXR0YWNobWVudFN0YXRlQgPgQQMSIAoTZXh0ZXJuYWxfaXBfYWRkcmVzcxgCIAEoCUID4EEDEhkKB21lc3NhZ2UYAyABKAlCA+BBA0gAiAEBQgoKCF9tZXNzYWdlKqUBChxFeHRlcm5hbElQQXR0YWNobWVudEVuZHBvaW50Ei8KK0VYVEVSTkFMX0lQX0FUVEFDSE1FTlRfRU5EUE9JTlRfVU5TUEVDSUZJRUQQABInCiNFWFRFUk5BTF9JUF9BVFRBQ0hNRU5UX0VORFBPSU5UX0FQSRABEisKJ0VYVEVSTkFMX0lQX0FUVEFDSE1FTlRfRU5EUE9JTlRfSU5HUkVTUxACKu8BChlFeHRlcm5hbElQQXR0YWNobWVudFN0YXRlEiwKKEVYVEVSTkFMX0lQX0FUVEFDSE1FTlRfU1RBVEVfVU5TUEVDSUZJRUQQABIoCiRFWFRFUk5BTF9JUF9BVFRBQ0hNRU5UX1NUQVRFX1BFTkRJTkcQARImCiJFWFRFUk5BTF9JUF9BVFRBQ0hNRU5UX1NUQVRFX1JFQURZEAISJwojRVhURVJOQUxfSVBfQVRUQUNITUVOVF9TVEFURV9GQUlMRUQQAxIpCiVFWFRFUk5BTF9JUF9BVFRBQ0hNRU5UX1NUQVRFX0RFTEVUSU5HEARiBnByb3RvMw", [file_google_api_field_behavior, file_osac_public_v1_metadata_type, file_osac_public_v1_baremetal_instance_type, file_osac_public_v1_cluster_type, file_osac_public_v1_compute_instance_type, file_osac_public_v1_external_ip_type]);

/**
 * Represents a binding between an ExternalIP and a target resource.
 *
 * An ExternalIPAttachment is a first-class resource that manages the attach/detach lifecycle
 * independently from the ExternalIP allocation lifecycle. Creating an ExternalIPAttachment triggers
 * the attach workflow; deleting it triggers the detach workflow.
 *
 * The binding is immutable: to change the target, delete the attachment and create a new one.
 * The oneof target field supports ComputeInstance, Cluster, and BareMetalInstance targets.
 *
 * For cluster targets, the target_endpoint field specifies which cluster endpoint receives the
 * external IP (API server or ingress). An ExternalIPAttachment can be created before the cluster
 * is ready and will activate automatically once the cluster's VIP is available.
 *
 * Lifecycle: PENDING (attach in progress) -> READY (attached and routing traffic) -> DELETING
 * (detach in progress). FAILED is a terminal error state that retries via the standard
 * provisioning lifecycle with exponential backoff.
 *
 * @generated from message osac.public.v1.ExternalIPAttachment
 */
export type ExternalIPAttachment = Message<"osac.public.v1.ExternalIPAttachment"> & {
  /**
   * Unique identifier of the external IP attachment.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the external IP attachment, including name, labels, and timestamps.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired configuration of the external IP attachment (user-specified).
   *
   * @generated from field: osac.public.v1.ExternalIPAttachmentSpec spec = 3;
   */
  spec?: ExternalIPAttachmentSpec | undefined;

  /**
   * Current state of the external IP attachment (system-provided, read-only).
   *
   * @generated from field: osac.public.v1.ExternalIPAttachmentStatus status = 4;
   */
  status?: ExternalIPAttachmentStatus | undefined;
};

/**
 * Describes the message osac.public.v1.ExternalIPAttachment.
 * Use `create(ExternalIPAttachmentSchema)` to create a new message.
 */
export const ExternalIPAttachmentSchema: GenMessage<ExternalIPAttachment> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_external_ip_attachment_type, 0);

/**
 * Defines the desired configuration for an ExternalIPAttachment.
 *
 * All fields are required and immutable after creation. The external_ip must reference an
 * existing ExternalIP in ALLOCATED state. The target must reference a valid resource that
 * supports external IP attachment.
 *
 * @generated from message osac.public.v1.ExternalIPAttachmentSpec
 */
export type ExternalIPAttachmentSpec = Message<"osac.public.v1.ExternalIPAttachmentSpec"> & {
  /**
   * ExternalIP reference to attach. Required and immutable after creation.
   *
   * Must reference an existing ExternalIP in ALLOCATED state that is not already
   * attached (status.attached == false). Only one ExternalIPAttachment may exist per ExternalIP.
   *
   * @generated from field: osac.public.v1.ExternalIPLocalReference external_ip = 1;
   */
  externalIp?: ExternalIPLocalReference | undefined;

  /**
   * Target resource to attach the external IP to. Exactly one target field must be set.
   * Required and immutable after creation.
   *
   * @generated from oneof osac.public.v1.ExternalIPAttachmentSpec.target
   */
  target: {
    /**
     * ComputeInstance reference to attach this external IP to.
     *
     * Must reference an existing ComputeInstance in RUNNING state. Only one
     * ExternalIPAttachment may exist per ComputeInstance.
     *
     * @generated from field: osac.public.v1.ComputeInstanceLocalReference compute_instance = 2;
     */
    value: ComputeInstanceLocalReference;
    case: "computeInstance";
  } | {
    /**
     * Cluster reference to attach this external IP to.
     *
     * Must reference an existing Cluster. The target_endpoint field is required
     * when targeting a cluster to specify which endpoint (API or ingress) receives the
     * external IP. The attachment can be created before the cluster is ready and will
     * activate once the cluster's VIP is available.
     *
     * @generated from field: osac.public.v1.ClusterLocalReference cluster = 3;
     */
    value: ClusterLocalReference;
    case: "cluster";
  } | {
    /**
     * BareMetalInstance reference to attach this external IP to.
     *
     * Must reference an existing BareMetalInstance. DNAT rules will be configured
     * to forward traffic from the external IP to the bare-metal instance's internal IP.
     *
     * @generated from field: osac.public.v1.BareMetalInstanceLocalReference baremetal_instance = 4;
     */
    value: BareMetalInstanceLocalReference;
    case: "baremetalInstance";
  } | { case: undefined; value?: undefined };

  /**
   * Cluster endpoint to attach the external IP to. Required when target is cluster.
   *
   * Specifies whether the external IP should be routed to the cluster's API server endpoint
   * or its ingress endpoint. Ignored for non-cluster targets. Immutable after creation.
   *
   * @generated from field: osac.public.v1.ExternalIPAttachmentEndpoint target_endpoint = 5;
   */
  targetEndpoint: ExternalIPAttachmentEndpoint;
};

/**
 * Describes the message osac.public.v1.ExternalIPAttachmentSpec.
 * Use `create(ExternalIPAttachmentSpecSchema)` to create a new message.
 */
export const ExternalIPAttachmentSpecSchema: GenMessage<ExternalIPAttachmentSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_external_ip_attachment_type, 1);

/**
 * Represents the current operational state of an ExternalIPAttachment.
 *
 * Status is system-provided and read-only. Users cannot modify status fields directly; the
 * system updates them based on reconciliation of the spec and feedback from the cluster
 * controller.
 *
 * @generated from message osac.public.v1.ExternalIPAttachmentStatus
 */
export type ExternalIPAttachmentStatus = Message<"osac.public.v1.ExternalIPAttachmentStatus"> & {
  /**
   * Current lifecycle state of the external IP attachment.
   *
   * @generated from field: osac.public.v1.ExternalIPAttachmentState state = 1;
   */
  state: ExternalIPAttachmentState;

  /**
   * Allocated IP address from the parent ExternalIP.
   *
   * Populated for convenience once the attachment reaches READY state. Mirrors the address
   * field from the referenced ExternalIP's status.
   *
   * @generated from field: string external_ip_address = 2;
   */
  externalIpAddress: string;

  /**
   * Human-readable message providing additional details about the current state.
   *
   * For PENDING state, may contain progress information. For FAILED state, contains the
   * error details. Typically empty for READY state.
   *
   * @generated from field: optional string message = 3;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.public.v1.ExternalIPAttachmentStatus.
 * Use `create(ExternalIPAttachmentStatusSchema)` to create a new message.
 */
export const ExternalIPAttachmentStatusSchema: GenMessage<ExternalIPAttachmentStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_external_ip_attachment_type, 2);

/**
 * Endpoint type for cluster-targeted ExternalIPAttachments.
 *
 * When attaching an external IP to a cluster, this enum specifies which cluster endpoint
 * receives the DNAT rule.
 *
 * @generated from enum osac.public.v1.ExternalIPAttachmentEndpoint
 */
export enum ExternalIPAttachmentEndpoint {
  /**
   * Endpoint is unknown or has not been specified.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_ENDPOINT_UNSPECIFIED = 0;
   */
  EXTERNAL_IP_ATTACHMENT_ENDPOINT_UNSPECIFIED = 0,

  /**
   * The cluster's API server endpoint.
   *
   * The external IP will be routed to the cluster's Kubernetes API server VIP, making the
   * cluster API reachable from outside the VirtualNetwork.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_ENDPOINT_API = 1;
   */
  EXTERNAL_IP_ATTACHMENT_ENDPOINT_API = 1,

  /**
   * The cluster's ingress endpoint.
   *
   * The external IP will be routed to the cluster's ingress controller VIP, making
   * applications hosted on the cluster reachable from outside the VirtualNetwork.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_ENDPOINT_INGRESS = 2;
   */
  EXTERNAL_IP_ATTACHMENT_ENDPOINT_INGRESS = 2,
}

/**
 * Describes the enum osac.public.v1.ExternalIPAttachmentEndpoint.
 */
export const ExternalIPAttachmentEndpointSchema: GenEnum<ExternalIPAttachmentEndpoint> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_external_ip_attachment_type, 0);

/**
 * Lifecycle states for ExternalIPAttachment resources.
 *
 * State transitions: UNSPECIFIED -> PENDING -> READY. On deletion: any state -> DELETING.
 * FAILED can occur from PENDING and retries automatically via the provisioning lifecycle.
 *
 * @generated from enum osac.public.v1.ExternalIPAttachmentState
 */
export enum ExternalIPAttachmentState {
  /**
   * State is unknown or has not been determined yet.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_STATE_UNSPECIFIED = 0;
   */
  EXTERNAL_IP_ATTACHMENT_STATE_UNSPECIFIED = 0,

  /**
   * The attachment is being provisioned (attach workflow in progress).
   *
   * The system is binding the ExternalIP's allocated address to the target resource. This
   * involves creating DNAT rules or MetalLB LoadBalancer Services depending on the target type.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_STATE_PENDING = 1;
   */
  EXTERNAL_IP_ATTACHMENT_STATE_PENDING = 1,

  /**
   * The attachment is active and the target is reachable via the external IP address.
   *
   * The ExternalIP's allocated address is bound to the target resource and actively routing
   * traffic. The parent ExternalIP's status.attached is set to true.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_STATE_READY = 2;
   */
  EXTERNAL_IP_ATTACHMENT_STATE_READY = 2,

  /**
   * The attachment failed. Check status.message for error details.
   *
   * The provisioning lifecycle retries automatically with exponential backoff.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_STATE_FAILED = 3;
   */
  EXTERNAL_IP_ATTACHMENT_STATE_FAILED = 3,

  /**
   * The attachment is being deprovisioned (detach workflow in progress).
   *
   * Triggered by deletion of the ExternalIPAttachment resource. The system unbinds the
   * address from the target and cleans up DNAT rules or MetalLB Services.
   * On completion, the parent ExternalIP's status.attached is set to false.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_STATE_DELETING = 4;
   */
  EXTERNAL_IP_ATTACHMENT_STATE_DELETING = 4,
}

/**
 * Describes the enum osac.public.v1.ExternalIPAttachmentState.
 */
export const ExternalIPAttachmentStateSchema: GenEnum<ExternalIPAttachmentState> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_external_ip_attachment_type, 1);
