//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/project_membership_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { UserReference } from "./user_type_pb";
import { file_osac_public_v1_user_type } from "./user_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/project_membership_type.proto.
 */
export const file_osac_public_v1_project_membership_type: GenFile = /*@__PURE__*/
  fileDesc("Cixvc2FjL3B1YmxpYy92MS9wcm9qZWN0X21lbWJlcnNoaXBfdHlwZS5wcm90bxIOb3NhYy5wdWJsaWMudjEiuQEKEVByb2plY3RNZW1iZXJzaGlwEgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESMwoEc3BlYxgDIAEoCzIlLm9zYWMucHVibGljLnYxLlByb2plY3RNZW1iZXJzaGlwU3BlYxI3CgZzdGF0dXMYBCABKAsyJy5vc2FjLnB1YmxpYy52MS5Qcm9qZWN0TWVtYmVyc2hpcFN0YXR1cyJ6ChVQcm9qZWN0TWVtYmVyc2hpcFNwZWMSMwoEcm9sZRgCIAEoDjIlLm9zYWMucHVibGljLnYxLlByb2plY3RNZW1iZXJzaGlwUm9sZRIsCgV1c2VycxgDIAMoCzIdLm9zYWMucHVibGljLnYxLlVzZXJSZWZlcmVuY2UicgoXUHJvamVjdE1lbWJlcnNoaXBTdGF0dXMSNQoFc3RhdGUYASABKA4yJi5vc2FjLnB1YmxpYy52MS5Qcm9qZWN0TWVtYmVyc2hpcFN0YXRlEhQKB21lc3NhZ2UYAiABKAlIAIgBAUIKCghfbWVzc2FnZSqJAQoVUHJvamVjdE1lbWJlcnNoaXBSb2xlEicKI1BST0pFQ1RfTUVNQkVSU0hJUF9ST0xFX1VOU1BFQ0lGSUVEEAASIgoeUFJPSkVDVF9NRU1CRVJTSElQX1JPTEVfVklFV0VSEAESIwofUFJPSkVDVF9NRU1CRVJTSElQX1JPTEVfTUFOQUdFUhACKrEBChZQcm9qZWN0TWVtYmVyc2hpcFN0YXRlEigKJFBST0pFQ1RfTUVNQkVSU0hJUF9TVEFURV9VTlNQRUNJRklFRBAAEiQKIFBST0pFQ1RfTUVNQkVSU0hJUF9TVEFURV9QRU5ESU5HEAESIgoeUFJPSkVDVF9NRU1CRVJTSElQX1NUQVRFX1JFQURZEAISIwofUFJPSkVDVF9NRU1CRVJTSElQX1NUQVRFX0ZBSUxFRBADYgZwcm90bzM", [file_osac_public_v1_metadata_type, file_osac_public_v1_user_type]);

/**
 * ProjectMembership represents a member's association with a project and their role within it.
 *
 * @generated from message osac.public.v1.ProjectMembership
 */
export type ProjectMembership = Message<"osac.public.v1.ProjectMembership"> & {
  /**
   * Unique identifier of the project membership.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Object metadata.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired state of the project membership.
   *
   * @generated from field: osac.public.v1.ProjectMembershipSpec spec = 3;
   */
  spec?: ProjectMembershipSpec | undefined;

  /**
   * Observed state of the project membership.
   *
   * @generated from field: osac.public.v1.ProjectMembershipStatus status = 4;
   */
  status?: ProjectMembershipStatus | undefined;
};

/**
 * Describes the message osac.public.v1.ProjectMembership.
 * Use `create(ProjectMembershipSchema)` to create a new message.
 */
export const ProjectMembershipSchema: GenMessage<ProjectMembership> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_project_membership_type, 0);

/**
 * Describes the members of a project.
 *
 * @generated from message osac.public.v1.ProjectMembershipSpec
 */
export type ProjectMembershipSpec = Message<"osac.public.v1.ProjectMembershipSpec"> & {
  /**
   * Role of the members in the project. This indicates whether the members are viewers, managers, etc.
   *
   * @generated from field: osac.public.v1.ProjectMembershipRole role = 2;
   */
  role: ProjectMembershipRole;

  /**
   * References to the users that are members of the project.
   *
   * @generated from field: repeated osac.public.v1.UserReference users = 3;
   */
  users: UserReference[];
};

/**
 * Describes the message osac.public.v1.ProjectMembershipSpec.
 * Use `create(ProjectMembershipSpecSchema)` to create a new message.
 */
export const ProjectMembershipSpecSchema: GenMessage<ProjectMembershipSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_project_membership_type, 1);

/**
 * Describes the observed state of a project membership.
 *
 * @generated from message osac.public.v1.ProjectMembershipStatus
 */
export type ProjectMembershipStatus = Message<"osac.public.v1.ProjectMembershipStatus"> & {
  /**
   * Current state of the project membership.
   *
   * @generated from field: osac.public.v1.ProjectMembershipState state = 1;
   */
  state: ProjectMembershipState;

  /**
   * Human-readable message providing additional details about the current state. For example, if the state is
   * FAILED, this field may explain why the synchronization with the identity provider failed.
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.public.v1.ProjectMembershipStatus.
 * Use `create(ProjectMembershipStatusSchema)` to create a new message.
 */
export const ProjectMembershipStatusSchema: GenMessage<ProjectMembershipStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_project_membership_type, 2);

/**
 * Describes the role of a member in a project.
 *
 * @generated from enum osac.public.v1.ProjectMembershipRole
 */
export enum ProjectMembershipRole {
  /**
   * Default value, should not be used.
   *
   * @generated from enum value: PROJECT_MEMBERSHIP_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The member can view the project and its resources.
   *
   * @generated from enum value: PROJECT_MEMBERSHIP_ROLE_VIEWER = 1;
   */
  VIEWER = 1,

  /**
   * The member can manage the project, including adding/removing other members.
   *
   * @generated from enum value: PROJECT_MEMBERSHIP_ROLE_MANAGER = 2;
   */
  MANAGER = 2,
}

/**
 * Describes the enum osac.public.v1.ProjectMembershipRole.
 */
export const ProjectMembershipRoleSchema: GenEnum<ProjectMembershipRole> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_project_membership_type, 0);

/**
 * Describes the state of a project membership.
 *
 * @generated from enum osac.public.v1.ProjectMembershipState
 */
export enum ProjectMembershipState {
  /**
   * Default value, should not be used.
   *
   * @generated from enum value: PROJECT_MEMBERSHIP_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The project membership is pending synchronization with the identity provider.
   *
   * @generated from enum value: PROJECT_MEMBERSHIP_STATE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * The project membership is ready and the member has the specified permissions.
   *
   * @generated from enum value: PROJECT_MEMBERSHIP_STATE_READY = 2;
   */
  READY = 2,

  /**
   * The project membership failed to synchronize with the identity provider.
   *
   * @generated from enum value: PROJECT_MEMBERSHIP_STATE_FAILED = 3;
   */
  FAILED = 3,
}

/**
 * Describes the enum osac.public.v1.ProjectMembershipState.
 */
export const ProjectMembershipStateSchema: GenEnum<ProjectMembershipState> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_project_membership_type, 1);
