//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/storage_common_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file osac/public/v1/storage_common_type.proto.
 */
export const file_osac_public_v1_storage_common_type: GenFile = /*@__PURE__*/
  fileDesc("Cihvc2FjL3B1YmxpYy92MS9zdG9yYWdlX2NvbW1vbl90eXBlLnByb3RvEg5vc2FjLnB1YmxpYy52MSppCg9TdG9yYWdlUHJvdG9jb2wSIAocU1RPUkFHRV9QUk9UT0NPTF9VTlNQRUNJRklFRBAAEhgKFFNUT1JBR0VfUFJPVE9DT0xfTkZTEAESGgoWU1RPUkFHRV9QUk9UT0NPTF9CTE9DSxACYgZwcm90bzM");

/**
 * Identifies the storage protocol used by storage backends and volumes.
 *
 * @generated from enum osac.public.v1.StorageProtocol
 */
export enum StorageProtocol {
  /**
   * Protocol is unknown or has not been specified.
   *
   * @generated from enum value: STORAGE_PROTOCOL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * NFS (Network File System) protocol for file-based storage access.
   *
   * @generated from enum value: STORAGE_PROTOCOL_NFS = 1;
   */
  NFS = 1,

  /**
   * Block storage protocol for volume-based storage access.
   *
   * @generated from enum value: STORAGE_PROTOCOL_BLOCK = 2;
   */
  BLOCK = 2,
}

/**
 * Describes the enum osac.public.v1.StorageProtocol.
 */
export const StorageProtocolSchema: GenEnum<StorageProtocol> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_storage_common_type, 0);
