//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/virtual_network_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/virtual_network_type.proto.
 */
export const file_osac_public_v1_virtual_network_type: GenFile = /*@__PURE__*/
  fileDesc("Cilvc2FjL3B1YmxpYy92MS92aXJ0dWFsX25ldHdvcmtfdHlwZS5wcm90bxIOb3NhYy5wdWJsaWMudjEisAEKDlZpcnR1YWxOZXR3b3JrEgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESMAoEc3BlYxgDIAEoCzIiLm9zYWMucHVibGljLnYxLlZpcnR1YWxOZXR3b3JrU3BlYxI0CgZzdGF0dXMYBCABKAsyJC5vc2FjLnB1YmxpYy52MS5WaXJ0dWFsTmV0d29ya1N0YXR1cyJqChJWaXJ0dWFsTmV0d29ya1NwZWMSGwoJaXB2NF9jaWRyGAEgASgJQgPgQQVIAIgBARIbCglpcHY2X2NpZHIYAiABKAlCA+BBBUgBiAEBQgwKCl9pcHY0X2NpZHJCDAoKX2lwdjZfY2lkciJsChRWaXJ0dWFsTmV0d29ya1N0YXR1cxIyCgVzdGF0ZRgBIAEoDjIjLm9zYWMucHVibGljLnYxLlZpcnR1YWxOZXR3b3JrU3RhdGUSFAoHbWVzc2FnZRgCIAEoCUgAiAEBQgoKCF9tZXNzYWdlIjgKHFZpcnR1YWxOZXR3b3JrTG9jYWxSZWZlcmVuY2USCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCSqiAQoTVmlydHVhbE5ldHdvcmtTdGF0ZRIlCiFWSVJUVUFMX05FVFdPUktfU1RBVEVfVU5TUEVDSUZJRUQQABIhCh1WSVJUVUFMX05FVFdPUktfU1RBVEVfUEVORElORxABEh8KG1ZJUlRVQUxfTkVUV09SS19TVEFURV9SRUFEWRACEiAKHFZJUlRVQUxfTkVUV09SS19TVEFURV9GQUlMRUQQA2IGcHJvdG8z", [file_google_api_field_behavior, file_osac_public_v1_metadata_type]);

/**
 * Represents a tenant-isolated virtual network.
 *
 * VirtualNetwork provides network isolation for compute instances within a region. Each VirtualNetwork is backed
 * by a specific NetworkClass implementation strategy (e.g., "udn-net" for User-Defined Networks, "phys-net" for
 * physical network infrastructure).
 *
 * VirtualNetworks support flexible IP addressing:
 * - IPv4-only: Set ipv4_cidr, leave ipv6_cidr empty
 * - IPv6-only: Set ipv6_cidr, leave ipv4_cidr empty
 * - Dual-stack: Set both ipv4_cidr and ipv6_cidr
 *
 * The selected NetworkClass must support the requested IP addressing mode via its capabilities.
 *
 * Tenant isolation is enforced via the standard Metadata tenant field. VirtualNetworks are scoped to
 * a single region and cannot span multiple regions.
 *
 * @generated from message osac.public.v1.VirtualNetwork
 */
export type VirtualNetwork = Message<"osac.public.v1.VirtualNetwork"> & {
  /**
   * Unique identifier of the virtual network.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the virtual network, including name, labels, tenant, and timestamps.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired configuration of the virtual network (user-modifiable).
   *
   * @generated from field: osac.public.v1.VirtualNetworkSpec spec = 3;
   */
  spec?: VirtualNetworkSpec | undefined;

  /**
   * Current state of the virtual network (system-provided, read-only).
   *
   * @generated from field: osac.public.v1.VirtualNetworkStatus status = 4;
   */
  status?: VirtualNetworkStatus | undefined;
};

/**
 * Describes the message osac.public.v1.VirtualNetwork.
 * Use `create(VirtualNetworkSchema)` to create a new message.
 */
export const VirtualNetworkSchema: GenMessage<VirtualNetwork> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_virtual_network_type, 0);

/**
 * Defines the desired configuration for a VirtualNetwork.
 *
 * The spec contains user-specified parameters that define how the network should be configured. These fields
 * follow a declarative model where users specify the desired state and the system reconciles to match it.
 *
 * @generated from message osac.public.v1.VirtualNetworkSpec
 */
export type VirtualNetworkSpec = Message<"osac.public.v1.VirtualNetworkSpec"> & {
  /**
   * IPv4 CIDR block for this network. Optional for IPv6-only networks. Immutable after creation.
   *
   * Must be valid CIDR notation. Validation enforced at service layer.
   * The CIDR block should be appropriately sized for the expected number of compute instances.
   *
   * Example: "10.0.0.0/16", "192.168.0.0/24"
   *
   * Leave empty when creating an IPv6-only network.
   *
   * @generated from field: optional string ipv4_cidr = 1;
   */
  ipv4Cidr?: string | undefined;

  /**
   * IPv6 CIDR block for this network. Optional for IPv4-only networks. Immutable after creation.
   *
   * Must be valid CIDR notation. Validation enforced at service layer.
   * IPv6 addresses should follow standard allocation practices for tenant networks.
   *
   * Example: "2001:db8::/48", "fd00::/64"
   *
   * Leave empty when creating an IPv4-only network.
   *
   * @generated from field: optional string ipv6_cidr = 2;
   */
  ipv6Cidr?: string | undefined;
};

/**
 * Describes the message osac.public.v1.VirtualNetworkSpec.
 * Use `create(VirtualNetworkSpecSchema)` to create a new message.
 */
export const VirtualNetworkSpecSchema: GenMessage<VirtualNetworkSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_virtual_network_type, 1);

/**
 * Represents the current operational state of a VirtualNetwork.
 *
 * Status is system-provided and read-only. Users cannot modify status fields directly; the system updates them
 * based on the reconciliation of the spec.
 *
 * @generated from message osac.public.v1.VirtualNetworkStatus
 */
export type VirtualNetworkStatus = Message<"osac.public.v1.VirtualNetworkStatus"> & {
  /**
   * Current lifecycle state of the virtual network.
   *
   * @generated from field: osac.public.v1.VirtualNetworkState state = 1;
   */
  state: VirtualNetworkState;

  /**
   * Human-readable message providing additional details about the current state.
   *
   * For PENDING state, this might contain progress information like "Allocating IP address space" or
   * "Configuring network backend".
   *
   * For FAILED state, this contains error details explaining what went wrong, such as "Invalid CIDR range" or
   * "NetworkClass does not support dual-stack".
   *
   * For READY state, this is typically empty or contains confirmation like "Network ready for compute instances".
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.public.v1.VirtualNetworkStatus.
 * Use `create(VirtualNetworkStatusSchema)` to create a new message.
 */
export const VirtualNetworkStatusSchema: GenMessage<VirtualNetworkStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_virtual_network_type, 2);

/**
 * Local reference to a VirtualNetwork resource.
 *
 * @generated from message osac.public.v1.VirtualNetworkLocalReference
 */
export type VirtualNetworkLocalReference = Message<"osac.public.v1.VirtualNetworkLocalReference"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message osac.public.v1.VirtualNetworkLocalReference.
 * Use `create(VirtualNetworkLocalReferenceSchema)` to create a new message.
 */
export const VirtualNetworkLocalReferenceSchema: GenMessage<VirtualNetworkLocalReference> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_virtual_network_type, 3);

/**
 * Lifecycle states for VirtualNetwork resources.
 *
 * State transitions typically follow: UNSPECIFIED -> PENDING -> READY, with FAILED as a terminal error state
 * that may require user intervention or resource recreation.
 *
 * @generated from enum osac.public.v1.VirtualNetworkState
 */
export enum VirtualNetworkState {
  /**
   * State is unknown or has not been determined yet. This is the default state before initialization.
   *
   * @generated from enum value: VIRTUAL_NETWORK_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The virtual network is being initialized and is not ready for use yet.
   *
   * During this state, the system is:
   * - Validating CIDR blocks
   * - Checking NetworkClass compatibility
   * - Allocating IP address space
   * - Configuring the network backend
   *
   * Compute instances cannot be attached to networks in PENDING state.
   *
   * @generated from enum value: VIRTUAL_NETWORK_STATE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * The virtual network is fully operational and ready for compute instances to attach.
   *
   * In this state:
   * - CIDR blocks are allocated and configured
   * - Network backend is ready
   * - Compute instances can be created and attached
   * - Network isolation and routing are active
   *
   * @generated from enum value: VIRTUAL_NETWORK_STATE_READY = 2;
   */
  READY = 2,

  /**
   * The virtual network has encountered an error and is unusable.
   *
   * Common failure reasons include:
   * - Invalid CIDR notation
   * - CIDR block conflicts with existing networks
   * - NetworkClass does not support requested capabilities (e.g., dual-stack not supported)
   * - NetworkClass is not in READY state
   * - Network backend configuration error
   *
   * The status.message field will contain specific error details. Failed networks typically require deletion
   * and recreation with corrected parameters.
   *
   * @generated from enum value: VIRTUAL_NETWORK_STATE_FAILED = 3;
   */
  FAILED = 3,
}

/**
 * Describes the enum osac.public.v1.VirtualNetworkState.
 */
export const VirtualNetworkStateSchema: GenEnum<VirtualNetworkState> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_virtual_network_type, 0);
