{{- if .Values.serviceAccount.node.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csi-driver.nodeServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: node
{{- end }}
