{{- if .Values.fakeCrds.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusteruserdefinednetworks.k8s.ovn.org
  labels:
    {{- include "osac-infra.labels" . | nindent 4 }}
spec:
  group: k8s.ovn.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  scope: Cluster
  names:
    plural: clusteruserdefinednetworks
    singular: clusteruserdefinednetwork
    kind: ClusterUserDefinedNetwork
    shortNames:
      - cudn
{{- end }}
