{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: osac-infra-kafka-config
  labels:
    {{- include "osac-infra.labels" . | nindent 4 }}
data:
  kafka-cluster.yaml: |
    apiVersion: kafka.strimzi.io/v1
    kind: KafkaNodePool
    metadata:
      name: dual-role
      namespace: osac-kafka
      labels:
        strimzi.io/cluster: osac-kafka
    spec:
      replicas: {{ .Values.kafka.replicas }}
      roles:
        - controller
        - broker
      storage:
        type: persistent-claim
        size: {{ .Values.kafka.storage.size }}
        deleteClaim: false
    ---
    apiVersion: kafka.strimzi.io/v1
    kind: Kafka
    metadata:
      name: osac-kafka
      namespace: osac-kafka
      annotations:
        strimzi.io/kraft: enabled
        strimzi.io/node-pools: enabled
    spec:
      kafka:
        version: {{ .Values.kafka.version | quote }}
        metadataVersion: {{ .Values.kafka.metadataVersion | quote }}
        listeners:
          - name: tls
            port: 9093
            type: internal
            tls: true
            authentication:
              type: scram-sha-512
        config:
          offsets.topic.replication.factor: {{ .Values.kafka.replicas }}
          transaction.state.log.replication.factor: {{ .Values.kafka.replicas }}
          transaction.state.log.min.isr: {{ min .Values.kafka.replicas 2 }}
          default.replication.factor: {{ .Values.kafka.replicas }}
          min.insync.replicas: {{ min .Values.kafka.replicas 2 }}
        authorization:
          type: simple
      entityOperator:
        topicOperator: {}
        userOperator: {}
{{- end }}
